### ISSUE TITLE
invalid definition for UTM 32N (maibe fo other zones)

### ISSUE THREAD

**Issue by kolovsky** [OpenOrienteering/mapper#524] opened 2015-10-07 13:14 UTC
If I set UTM 32 N Mapper use definition for 31N. I solve this problem so that I use PROJ.4 definition for all system.

**Comment by dg0yt** [comment] 2015-10-07 17:17
Duplicate of #432, which is now marked as a known issue for 0.5.96.

Note that "unstable" builds for testing are available from the openSUSE build service for [Linux](https://software.opensuse.org/download.html?project=home%3Adg0yt&package=openorienteering-mapper-unstable) and for [Windows](http://download.opensuse.org/repositories/home:/dg0yt/Windows/) (selfextracting ZIP).

**Closed** 2015-10-07 17:17 UTC
Labels: duplicate
