### ISSUE TITLE
Time stamp for added objects

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#700] opened 2016-06-15 22:48 UTC
Fieldwork with OOM 0.6.1 on a pad Windows 8.1.

When using one computer at office and one pad in the forest, and moving maps between them, I get confused sometimes and I can't remember if a specific object was done this day or previous, and similair questions. I end up producing one "filed version" every day and also one for "fine drawing at office". When there was too much field work one day so you cannot let these versions change, problems start to appear.

It would be great and reduce the need for producing manual versions if the program remembered what time each object was drawn. You must than also be able to show or hide objects drawn between different times. 

I have not tried "parts" but maybe that is some kind of same thing, but you must remember to make new parts and also know in what part you are. My suggestion lets the computer do that boring job.

Maybe it could open up for new better ways of field work. I guess OOM should not only be a tool for "sitting at the desk and have nice indoor job"? :)

**Comment by Abbe98** [comment] 2016-06-16 00:17
I think parts is exactly what you are looking for, my usual way of doing it:

1. create a new part when going outside(takes no time at all), include the date in the name.
2. later when doing the fine tuning at the desktop I move objects from the fieldwork part to the actual main one.

I don't think you can get much more help from the computer then that. 

The above solution aside I guess each object could get a timestamp witch could be shown somewhere when the object is selected.

**Comment by dg0yt** [comment] 2016-06-16 06:14
To do it once and completely, we would track:
- time of creation, and author 
- time of last modification, and editor
- the same meta data for symbols (maybe using "iof/oo" for the author field of supplied symbol sets).

A 32 bit UNIX time stamp should be a sufficient internal representation for the next 20 years.

This will add app. 100 KB ... 1 MB to a map file (1000 ... 10000 objects).

**Comment by Zerbembasqwibo** [comment] 2016-06-16 17:13
1 MB is nothing tomorrow.


2016-06-16 8:14 GMT+02:00 Kai Pastor <notifications@github.com>:

> To do it once and completely, we would track:
>
>    - time of creation, and author
>    - time of last modification, and editor
>    - the same meta data for symbols (maybe using "iof/oo" for the author
>    field of supplied symbol sets).
>
> A 32 bit UNIX time stamp should be a sufficient internal representation
> for the next 20 years.
>
> This will add app. 100 KB ... 1 MB to a map file (1000 ... 10000 objects).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenOrienteering/mapper/issues/700#issuecomment-226397037>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APa4D3Xsf24PKlGX8wRmQSk3Ac6dbu-Xks5qMOmvgaJpZM4I23tX>
> .
>



-- 

Skickat från min Xpensius Mulitfrekvensus supercoola telefon som
sprider massa dryg reklam till alla jag e-postar.

**Comment by Symbian9** [comment] 2016-06-16 19:38
Map parts is better way do that! 
I cant see needs do separate time stamps.

**Comment by Zerbembasqwibo** [comment] 2016-06-16 19:41
You walk in the field. By mistake you add a stone. When back home and of
course two weeks later, you start to wonder. You have been there, but the
day before, or? You can match timestamp with GPS track to realise if it was
a mistake or not.

2016-06-16 21:38 GMT+02:00 Symbian9 <notifications@github.com>:

> Map parts is better way do that!
> I cant see needs do separate time stamps.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenOrienteering/mapper/issues/700#issuecomment-226590909>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APa4D1euLx-7Xa0qL-7Q5g0C90D5DEQXks5qMaYhgaJpZM4I23tX>
> .
>



-- 

Skickat från min Xpensius Mulitfrekvensus supercoola telefon som
sprider massa dryg reklam till alla jag e-postar.

**Comment by Symbian9** [comment] 2016-06-16 19:52
@Zerbembasqwibo, you only need create separate mapparts with this name that related to fieldworks date. Thats all.

**Comment by Zerbembasqwibo** [comment] 2016-06-16 20:01
I must try that way of working with parts.

Probably my demands are too specific, but I guess I am not alone using OOM
in field, but another program at home?

2016-06-16 21:52 GMT+02:00 Symbian9 <notifications@github.com>:

> @Zerbembasqwibo <https://github.com/Zerbembasqwibo>, you only need create
> separate mapparts with this name that related to fieldworks date. Thats
> all.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenOrienteering/mapper/issues/700#issuecomment-226594452>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APa4D12W5IMvTYrz4v3PnINQVLyQnWAtks5qMalvgaJpZM4I23tX>
> .
>



-- 

Skickat från min Xpensius Mulitfrekvensus supercoola telefon som
sprider massa dryg reklam till alla jag e-postar.

**Comment by dl3sdo** [comment] 2016-06-16 21:43
I talked to Kai last weekend and had the same idea of adding time of creation and time of last modification. So, you are not alone with your proposal.

**Comment by dg0yt** [comment] 2016-06-19 13:44
Closing this as a duplicate of #324.

**Closed** 2016-06-19 13:45 UTC
Labels: duplicate
