### ISSUE TITLE
Wrong rotation of raster image templates with world files

### ISSUE THREAD

**Issue by SQ5TB** [OpenOrienteering/mapper#839] opened 2017-02-16 22:27 UTC
This bug occurs only in unstable version when grivation is not equal 0.
In my project I use Poland National Coordinate System "92" EPSG : 2180.
After opening raster and vector template this two layers doesn't fit together.

![oom_raster](https://cloud.githubusercontent.com/assets/7237381/23044103/0eb78376-f49f-11e6-9e79-afc64610e980.png)

Comparing maps in stable and unstable version of OOMapper it looks like wrong raster rotation.

![oom_raster2](https://cloud.githubusercontent.com/assets/7237381/23043963/88506ae6-f49e-11e6-8884-1fca6a039280.png)

My configuration
Mapper Version: Unstable 20170130
Operating System: Windows 10

**Comment by dg0yt** [comment] 2017-02-17 04:04
This looks like wrong sign. I wouldn't be surprised if Mapper 0.6.7 is the version which contains bugs, compared to 0.6.6 or unstable, because of changes before and after this release But each bug has very particular conditions. 

I do have difficulties to reproduce this issue.
- In which version of Mapper did you add the raster image?
- How did you align the raster image: Georeferenced, with passpoints, or by manual input?

73, Kai

**Comment by SQ5TB** [comment] 2017-02-17 07:55
1. Please create new project in unstable version.
2. My map area is located in central part of Poland. EPSG code 2180 (Gauss-Kruger projection, central meridian 19E, scale factor=0,9993). Reference point is within map area (SW corner)
3. Declination = 5.62 (grivation = 3,64)

![oom_raster3](https://cloud.githubusercontent.com/assets/7237381/23056931/0fe32eea-f4ee-11e6-9443-a7238e691da1.png)

4. I prepared 2 reference files:
a) raster from WMS (epsg 2180), format jpg + worldfile
b) vector (shp or dxf) reprojected to epsg:2180 using QGIS
5. Add this two files to project as template or import vector directly.
I didn't try other locations and projections. If you want I can prepare simple data.

Tnx, Boguslaw

**Comment by dg0yt** [comment] 2017-02-17 19:56
Thanks for the test files. This issue is probably limited to raster images with world files: The alignment is calculated each time template and the map are loaded. This affects not only unstable but also the the (tentative) release-0.6.8 branch.

**Comment by dg0yt** [comment] 2017-02-17 20:06
`git bisect` on the small release-0.6.8 branch points to cb51ac725c4fcdca146d2437212792344c712473 "Fix rotation calculation in qTransformToTemplateTransform()" which is 5428b503045c4b2a814ead8d9fd6940bee586c86 in the master branch. This the spot I expected.
I need to investigate if either this change was wrong, or if the world file interpretation also relied on the broken QTransform usage fixed in ecaca2f74f9b06965247bdfdf01bf21a11784124.

**Closed** 2017-02-18 10:49 UTC
Labels: known issues unstable

**Comment by dg0yt** [comment] 2017-02-18 11:31
New unstable packages show be available now or appear in a few minutes.
