### ISSUE TITLE
Broken .gpkg support

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1581] opened 2020-04-15 09:12 UTC
### Steps to reproduce
1. Opening a file with .raster.gpkg and .gpkg-templates in "master v20200411.3"

### Actual behaviour
.gpkg file format is no longer recognized, while .raster.gpkg is. Mapper casts a warning ("not recognized as supported file format") and does not load the .gpkg template (in contrast to v0.9.2)

### Expected behaviour
Treat the .gpkg as the vector format as earlier. (or communicate the necessary change in the naming convention?)

### Configuration
Mapper Version: master v20200411.3
Operating System: Win7

**Comment by dg0yt** [comment] 2020-04-15 21:24
I'm unable to reproduce this issue. What I did: 
In v0.9.2, I exported the complete map example as .gpkg vector data, and as .png raster graphics. Then I converted the .png to .raster.gpkg with gdalwarp -of GPKG. Now I added both gpkg files as templates, saved the file, closed Mapper, and started Mapper 20200411. Both templates load as expected. Also after saving/closing/opening, everything loads again as expected. 

I admit that I did this on Linux, with an older version of GDAL. But a quick test on Windows didn't indicate problems with vector gpkg files.

[#1581 broken gpkg support.zip](https://github.com/OpenOrienteering/mapper/files/4483781/1581.broken.gpkg.support.zip)

**Comment by mlerjen** [comment] 2020-04-16 20:39
I can reproduce the error with your sample data, 
![image](https://user-images.githubusercontent.com/15611653/79503950-515d2380-8032-11ea-8bb6-b4b69d27851a.png)

similar to the one I reported. 
![image](https://user-images.githubusercontent.com/15611653/79503151-f7a82980-8030-11ea-9313-093866f64b04.png)

Is the try to "read image data" an indication of the errors root? 

Here is my sample data, both .gpkgs are made with QGIS.
[Uploading Sample issue 1581.zip…]()

**Comment by dg0yt** [comment] 2020-04-17 05:24
I can reproduce the bug now, and I know what is going. There is still a missing piece of code for the case when neither the type of the data nor the absolute path of the template are known. This is mostly a transitional problem, maps saved with the new version save the type and thus do not exhibit the bug. However, I'm going to develop the missing piece.

**Closed** 2020-04-18 20:56 UTC
