### ISSUE TITLE
Remove template files when source file does not exist

### ISSUE THREAD

**Issue by arenol** [OpenOrienteering/mapper#591] opened 2016-02-08 18:54 UTC
As of version 0.6.20160113:

I'm unable to delete templates whose files no longer exist.  This is due to a dead lock:

You have to switch on a template in order to delete it.
You cannot switch on a template whose file does not exist.

A typical scenario of this bug is when an omap files is shared without the template files.

**Comment by dg0yt** [comment] 2016-02-08 21:29
Duplicate of #586.

**Closed by dg0yt** 2016-02-08 21:29 UTC
Labels: duplicate
