### ISSUE TITLE
Export to higher version of Ocad

### ISSUE THREAD

**Issue by zlenhart** [OpenOrienteering/mapper#868] opened 2017-05-06 07:19 UTC
Export to Ocad 8 looses georeference info (EPSG, rotation). 

### Steps to reproduce
1. Save georeferenced omap in Ocad format.
2. Open this ocd file in (higher version of) Ocad.
3. Check georeference parameters (compare with the original omap).
4. Open ocd file in OOM.
5. Save as omap.
6. Compare georeferenece parameters with the original omap file (or use original map as template).

### Actual behaviour
Georefernce lost

### Expected behaviour
Georeference correct

### Configuration
Mapper Version: 0.6.6
Operating System: Android 6.0.1

**Comment by dg0yt** [comment] 2017-05-07 19:17
Exporting to higher version is desired for a number of reasons. Georeferencing is covered in #596.

**Comment by magjo** [comment] 2017-05-08 19:35
Export to newer OCAD versions it also desired when sending a map for printing. Most people working with map printing does not know how to handle a map in omap format, but expect it to be in OCAD format.

**Comment by dg0yt** [comment] 2017-05-08 20:16
OTOH for reliable printing, PDF is much better suited than OCD. At least with CMYK, spot colors, and color management.

**Comment by magjo** [comment] 2017-05-09 06:32
Well, print using PDF would require the person (me) generating the PDF to know how to do it correctly (which I don't). Now I just send the OCAD file to the map printer and he adjusts the colors and symbols so that the map is printed the way it's expected. I believe this is the most common way of doing map (laser) printing in Sweden today.

**Comment by dg0yt** [comment] 2017-05-09 06:47
I don't dispute the fact that this is common. However, it is a very narrow approach: Despite the shortcomings in format documentation and the differences in internal concepts, Mapper is forced to use OCD as an intermediate format, and the printer must use Windows-only OCAD software and know the adjustments it has to apply to each color (and maybe symbol) in the OCD file.

The PDF approach is to produce a valid color-managed document, following a detailed public specification, which can be pre-flight checked in Adobe Acrobat (or similar), and handled by any professional print shop.

**Comment by magjo** [comment] 2017-05-09 07:01
I guess that the best would be that the print shop used Mapper directly and could print directly, or via any suitable format. The problem is that most people handling omaps for course setting does not have the sufficient knowledge about map printing to do the job correctly. I certainly don't and I gladly leave the print job to the print shop (which is specialized in map printing and does a very good job).

However, being able to export to such a common format for omaps as OCAD is desired for many reasons. The fact that the format is not documented only makes the task harder to solve, not less wanted.

**Comment by dg0yt** [comment] 2017-05-09 07:06
> However, being able to export to such a common format for omaps as OCAD is desired for many reasons. The fact that the format is not documented only makes the task harder to solve, not less wanted.

So we are back to:

> Exporting to higher version is desired for a number of reasons.

**Comment by lpechacek** [comment] 2017-10-15 20:01
FWIW here comes what I've learned about how OCAD handles georeferencing.

Georeferencing parameters entered in the [Scale and CRS dialog](https://www.ocad.com/wiki/ocad12/en/index.php?title=Create_a_New_Map#Set_Scale_and_Coordinate_System) are stored in si_ScalePar (type 1039) [parameters string](http://www.ocad.com/wiki/ocad11/en/?title=OCAD_11_File_Format#Parameter_Strings). Most of the parameter string values are easy to decipher as they correspond 1:1 to the dialog fields. This is well known and existing OOM file import code uses that knowledge.

However, trouble comes with the grid and zone parameter. It is not a standard EPSG code or something I would recognize but looks like some OCAD internal numbering(*). The number consists of two digit encoded country or system name and two to three digit zone name or CRS version. As you can see it's all in one. Belge 1972 / Belge Lambert 72 (EPSG 31300) is  4001, ETRS89 / Belgian Lambert 2005 (EPSG 3447) is 4002 and ETRS89 / Belgian Lambert 2008 (EPSG 3812) is 4003. S-JTSK / Krovak East North - SJTSK (EPSG 5514) covering the pre-WWII Czechoslovakia has two codes in OCAD world - 46001 for the Czechia and 47001 for Slovakia. UTM is represented as 20ZZ where ZZ is zone number. So UTM 33 is 2033. It's worth mentioning that some of the CRS' recognized by OCAD do not have an EPSG code assigned, or at least OCAD does not show the code.

It looks to me like it should be viable to establish correspondence between OCAD and OOM CRS' for UTM and datums with EPSG code assigned.

(*) I saw references to CooSys somewhere in OCAD. If you happen to know how it might be linked with the grid+zone numbers, let me know.

**Comment by dg0yt** [comment] 2017-10-15 23:20
@lpechacek The combined grid and zone parameter is already imported in some cases, including UTM: https://github.com/OpenOrienteering/mapper/blob/master/src/fileformats/ocd_file_import.cpp#L325

**Comment by dg0yt** [comment] 2018-10-08 06:16
Mostly done in `dev`.

**Closed by dg0yt** 2018-10-08 06:16 UTC
