### ISSUE TITLE
Cut & paste is influenced by georeferencing data

### ISSUE THREAD

**Issue by dorienj** [OpenOrienteering/mapper#845] opened 2017-03-16 09:44 UTC
### Steps to reproduce
Test A
1.  Create a new ISOM 1:10000 map
2.  Under "Map - Georeferencing" set local coordinates to (e.g.) 300000m E, 400000m N as you would for a UK national grid location
3.  Create a point feature e.g. a boulder
4.  Copy
5.  Paste

Test B
1.  Create a new map
2.  Under "Map - Georeferencing" set declination to (e.g.) 10 degrees
3.  Create a line object
4.  Copy
5.  Paste

### Actual behaviour
Under Test A, the point object is pasted close to the zero of the coordinate system.  (For UK coordinates, this point is near the Isles of Scilly and would require a map half the size of a football pitch.  Using UTM coordinates displays similar behaviour, except that the boulder is pasted a few hundred kilometers off the cost of Africa.)
Under Test B, the line object is rotated by the declination angle.

### Expected behaviour
According to http://www.openorienteering.org/mapper-manual/pages/edit_menu.html, the object should be pasted at the view midpoint.  There is no mention of rotation under any circumstances.

### Configuration
Mapper Version: 0.6.7
Operating System: Ubuntu 16.04 LTS

**Comment by dg0yt** [comment] 2017-03-17 05:29
Duplicate of #831 Copy-and-paste broken for georeferenced maps, which was closed with release 0.6.8.

**Closed by dg0yt** 2017-03-17 05:29 UTC
