### ISSUE TITLE
Georeferencing of UTM Zone is not keeped

### ISSUE THREAD

**Issue by zmalinowski1968** [OpenOrienteering/mapper#514] opened 2015-09-04 13:08 UTC
When I'm attaching first georeferenced OSM map as a template I'm supposed tu indicate a UTM belt. I'm in "34 N" which I'm typing in. I think it's working fine but at any moment later I'm entering "Georeferencing" screen it shows me "33 N" which is a bit frustrating.

**Comment by dg0yt** [comment] 2015-09-04 13:43
Duplicate of #432. (Already planned for next milestone, v0.5.97)

**Closed** 2015-09-04 13:43 UTC
Labels: duplicate
