### ISSUE TITLE
Saving in ocd9 and ocd10 generates broken files

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#1134] opened 2018-09-09 22:41 UTC
### Steps to reproduce
1. Save omap file in ocd9/ocd10 format (you can use _forest sample.omap_ from Mapper distributive)
2. Try to open ocd file by OCAD 10 (10.3.0.957 available for me for testing)

### Actual behaviour
1. Majority of objects are invisible. _Map -> Optimize/Repair_ doesn't help.
2. However such file can be opened by OCAD 12 and correctly saved in ocd9/ocd10 format.
3. ocd8 (old and new implementation) works well.

### Expected behaviour
Mapper generate files that can be opened by relevant OCAD version.

### Configuration
Mapper Version: 0.9.20180815 tested on Windows; fc9aa71efc838f9d8ebd26e71947363d0ed61c60 tested on Linux

**Comment by dg0yt** [comment] 2018-09-10 04:07
So far I only tested with OCAD 11 Viewer and later, which worked well. However I can reproduce major visibilty issues with OCAD 10 Viewer. Optimize/Repair removes all objects as "damaged".

**Comment by yevhenmazur** [comment] 2018-09-12 13:36
A lot of objects still recognising as damaged. They are visible now but Optimize/Repair procedure leads to their removal. I think this issue should be reopened.

**Comment by dg0yt** [comment] 2018-09-12 15:05
Since you created it, you could reopen it. I see the issues now with the complete map example/OCD 10.

**Comment by dg0yt** [comment] 2018-09-13 06:52
This issue is fixed now for the complete map example: We need include all control points (also curve handles) and unused space around text objects in the object extent. Please keep an eye on text objects: We rely on font metrics here, and I wouldn't be surprised if this depends on font availability and platform.

**Closed** 2018-10-06 07:56 UTC
Labels: known issues unstable
