### ISSUE TITLE
Vectorize lines detecting the plant density feature

### ISSUE THREAD

**Issue by AhmetPolat43** [OpenOrienteering/mapper#1827] opened 2020-12-27 20:23 UTC
Hello, I noticed something like this: I can get open areas from satellite images from the ability to detect vectors, but I cannot add them to the map as open space. Can you do something about it? I think can be added?
![1](https://user-images.githubusercontent.com/62382116/103179196-792ba900-489a-11eb-92c8-7fed1a12a297.jpg)
![2](https://user-images.githubusercontent.com/62382116/103179199-7cbf3000-489a-11eb-9a8d-041ecef6aeb2.jpg)
![3](https://user-images.githubusercontent.com/62382116/103179201-7f218a00-489a-11eb-81c1-b464e2dea118.jpg)
![3](https://user-images.githubusercontent.com/62382116/103179203-8183e400-489a-11eb-96e6-85050e5e459e.png)

**Comment by krticka** [comment] 2020-12-27 21:26
I think that creation of vector area objects is not supported at the moment. You can save this result as B/W image and use it as template.

**Comment by AhmetPolat43** [comment] 2020-12-27 21:41
> I think that creation of vector area objects is not supported at the moment. You can save this result as B/W image and use it as template.

I think it would be nice if supported

**Comment by AhmetPolat43** [comment] 2020-12-28 08:32
@dg0yt ?

**Comment by krticka** [comment] 2020-12-28 12:45
I don't think that converting such result to vector is useful. You can't use it directly for map creation, the result is very jagged and it will require extensive vertex editing. Redrawing raster template will be always faster.

**Comment by AhmetPolat43** [comment] 2020-12-28 13:22
> I don't think that converting such result to vector is useful. You can't use it directly for map creation, the result is very jagged and it will require extensive vertex editing. Redrawing raster template will be always faster.

Or you may be right. Would the images we get from here be useful?

**Comment by krticka** [comment] 2020-12-28 13:50
They can be, but in this particular case I would use satellite image directly in terrain.

**Comment by lpechacek** [comment] 2020-12-28 14:25
There is already a request for area processing in CoVe. Marking as duplicate of #1471.

**Closed by lpechacek** 2020-12-28 14:25 UTC
