### ISSUE TITLE
File format not recognized if try open OSM file

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1477] opened 2019-12-23 05:33 UTC
### Steps to reproduce

1. Launch *Mapper*;
2. Go to *"File > Open"*;
3. Set filter to *"All files"*;
4. Choose `*.osm` file;
5. Click on <kbd>Open</kbd>.

### Actual behaviour

If select any `*.osm` file in *"File > Open > All files"* dialog...

![pic.1](https://i.imgur.com/x21cZix.png)

... and try open it — Mapper said that *“File format not recognized”*

![pic.2](https://i.imgur.com/IEvP7OR.png)

If in *"File > Open"* set filters *"All maps"* or *"Geospatial vector data"* files with `*.osm` extensions not shown.

![pic.3](https://i.imgur.com/Ib66UgX.png)

![pic.4](https://i.imgur.com/WDL7JqA.png)

### Expected behaviour

OSM files should be opened as expected.

### Configuration

- **Mapper Version:** `master 0.9.20191221` (tagged as `master v20191221.17` on GitHub)
- **Operating System:** Debian 9.x, x86_64 (OBS build)

**Comment by lpechacek** [comment] 2019-12-23 13:06
@Symbian9, please educate me. How is this bug report different from issue 1476?

**Comment by Symbian9** [comment] 2019-12-23 13:57
> How is this bug report different from issue 1476?

This issue different because I try open OSM file throw dialog with *"All files"* filter and got warning message “File format not recognized”*.

In 1476 I mentioned that files with `*.osm` extension not recognized as supported file format throw file chooser dialogs with filters *"All maps"*, *"Geospatial vector data"*,  *Importable files" and *"Template files"* (OSM files in such case invisible in file chooser dialogs).

**Comment by lpechacek** [comment] 2019-12-23 14:05
OK, thanks for the explanation. I bet the two have the same root cause but let's keep the ticket open.

**Comment by dg0yt** [comment] 2019-12-24 00:19
Duplicate of #1476.

**Closed by dg0yt** 2019-12-24 00:19 UTC
Labels: bug
