### ISSUE TITLE
Select GPS source for Windows

### ISSUE THREAD

**Issue by PaulKaz** [OpenOrienteering/mapper#709] opened 2016-06-20 11:05 UTC
Select type of GPS source data from Location API or RAW data (NMEA) from serial port.
Qt support QNmeaPositionInfoSource since 5.2

**Comment by dg0yt** [comment] 2016-06-20 16:54
Duplicate of #422.

And Qt's serial port NMEA support on Windows [was added in 5.6](https://wiki.qt.io/New_Features_in_Qt_5.6).

**Closed by dg0yt** 2016-06-20 16:54 UTC
