### ISSUE TITLE
Cannot save as OCAD cause of internal error

### ISSUE THREAD

**Issue by kadirka** [OpenOrienteering/mapper#1991] opened 2021-10-07 23:09 UTC
### Steps to reproduce
1.After terrain work I took my omapper file from tablet to PC 
2.I opened file in Omapper
3.when I save as Ocad, it doesnt save, directly closes Omapper app by saving useless file named "mapname.ocd.HzKvio"

How can I save my work safely?

### Configuration
Mapper Version:0.9.5
Operating System:Windows 10 64-bit

**Comment by dg0yt** [comment] 2021-10-08 05:58
Sorry for the inconvenience. There seems to be a feature in the map which triggers some exceptional case in saving to OCD. I cannot look at the cause unless you provide the map, at least on a private channel, e.g. direct e-mail.

"mapname.ocd.HzKvio" is the temporary file which will replace the OCD file once writing was successful. This prevents loosing an existing file due to a rare crash like this one.

**Comment by lpechacek** [comment] 2021-10-08 06:42
This reminded me about #1856 but that bug is fixed in 0.9.5 release. @kadirka, you may still check the symbol set for "unusual" symbols while Kai is looking into the crash.

**Comment by kadirka** [comment] 2021-11-01 16:40
Thank you for advices.I solved the problem after I changed all the symbols into another symbol set.

Best Regards
Abdulkadir Köseoğlu

**Comment by dl3sdo** [comment] 2021-11-01 16:56
@kadirka: which symbol set caused the error (and which is the scale of your map)? Using a workaround does not solve the underlying issue which we would like to solve.

**Comment by d-ro** [comment] 2022-02-23 21:17
I am running into the same issue, even after replacing the symbol set. Is there any more guidance on which symbol(s) may be causing issues and a process to replace the set that solves this? Happy to provide map files securely. 
![image](https://user-images.githubusercontent.com/17025442/155409805-14a33ea0-26e2-4c4b-8726-871a15ecd9a8.png)

**Comment by lpechacek** [comment] 2022-02-24 07:02
Thanks for the comment and screenshot, @d-ro. The symptoms resemble a known problem described in issue #2015. You may try the workaround described at https://github.com/OpenOrienteering/mapper/issues/2015#issuecomment-1001419495 .

**Comment by hakongjerde** [comment] 2022-03-16 06:19
![image](https://user-images.githubusercontent.com/101694743/158528286-4d23dcc9-00c2-4bf8-bbdf-150176161f18.png)
I am also running into the same problem as above. I have tried the workarounds suggested, but no luck.
I have changed the symbolset to ISSprOM 2019-2 and the map is 1:4000. The map was originally created by someone else, while I am revising it. I am happy to provide a copy if anyone can take a look at it. thanks

**Comment by lpechacek** [comment] 2022-03-16 07:52
> I am happy to provide a copy if anyone can take a look at it. thanks

Sure! Please send the copy to the email listed on my profile and I'll have a look. Thanks!

**Comment by lpechacek** [comment] 2022-03-16 20:27
The fix for this issue has been merged into the main code branch and will be released in the next update.

In the meantime, Mapper development builds with this fix are available at https://dev.azure.com/OpenOrienteering/Mapper/_build/results?buildId=2528&view=artifacts&pathAsName=false&type=publishedArtifacts .

**Closed by lpechacek** 2022-03-16 20:27 UTC
Labels: crash

**Comment by mlerjen** [comment] 2022-03-16 21:00
That seems just to be a list of the artifacts. But how do I get the actual installation files? If I click on an item nothing happens...

**Comment by lpechacek** [comment] 2022-03-16 21:04
Ummm, there used to be a link to the .zip file containing all the artifacts on the page. I'll check it tomorrow and will let you know.

**Comment by mlerjen** [comment] 2022-03-16 21:14
@dl3sdo:  Indeed! @lpechacek: problem solved.

**Comment by mlerjen** [comment] 2022-03-16 21:19
![20220316_221603](https://user-images.githubusercontent.com/15611653/158692542-ffcdcd4a-11f7-4b10-9486-57bfcf7fd54f.jpg)
33cm ...

**Comment by Levente12345** [comment] 2022-12-22 21:23
Hi, 
Im having a similar problem by not being able to save my work in OCAD, only in OOM format. I tried to change symbol sets, but nothing helped. It was originally a foot-O map, but i  had to change and modify it to an MTBO map. Anyone has an idea how to save it in OCAD?
Thank you in advance!
Levente[
![issue screenshoot](https://user-images.githubusercontent.com/121263081/209228398-399047a6-26f5-4359-8cca-60ec9d62cefb.jpg)
](url)

**Comment by DuncSMTBO** [comment] 2023-01-23 22:29
I had similar issues to hakongjerde above. Removed all unsymbolised objects that came with dxf contour data, and gps traces. Problem solved

**Comment by hakken21** [comment] 2024-04-03 11:38
I have the same problem as hakongjerde above.
