### ISSUE TITLE
No more vector print function?

### ISSUE THREAD

**Issue by the-nipper** [OpenOrienteering/mapper#1924] opened 2021-03-25 21:20 UTC
### Steps to reproduce
1. Select Print... menu

### Actual behaviour
In Print... menu, only Raster Print button is functional, Vector and Select Print buttons are grayed out.

### Expected behaviour
In October 2020 (last time when I used Print... function), printing vector PDF on same system was still working.  

### Configuration
Mapper Version:0.9.5
Operating System:Ubuntu 18.04 Bionic Beaver, up-to-date patch state.

**Comment by jmacura** [comment] 2021-03-25 22:53
duplicate of #1914

**Comment by dg0yt** [comment] 2021-03-26 04:20
I'm sorry for this issue. 1914 is tagged to be found in the "known issues v0.9.5" which are linked from the release notes, and it is pinned at the top of the issues list. Do we also need to leave it in open state (because this is the default for search)?

**Comment by dg0yt** [comment] 2021-03-26 04:56
Or more accurately, this report is focused on **printing**, not **PDF**.

**Comment by the-nipper** [comment] 2021-03-26 05:55
Sorry for the duplicate.  I first skimmed over the list of already open issues, but I focused on the term Print rather than Export, so I didn't notice the 1914.  One may close my task and leave just the original one. 

In fact, vector graphics is also disabled for any of my 2 laser printers.  Thus it doesn't seem to relay on PDF export in particular, but is more general (well, printing is using same processing initial steps as PDF export...)

**Comment by dg0yt** [comment] 2021-03-26 06:12
Fine. 
We do not want to hide the known, resovled issues. I would like to have state between "open" and "closed". Maybe we can invent some better automation for closing issues, with tags and action.
I just verified that issue is resolved also for printing. I can trigger a master snapshot release in the next days.

**Closed by dg0yt** 2021-03-26 06:12 UTC
Labels: duplicate
