### ISSUE TITLE
Cannot save files to Dropbox folders

### ISSUE THREAD

**Issue by bagage** [OpenOrienteering/mapper#1029] opened 2018-01-02 19:43 UTC
(edited to refer to Dropbox folders instead of space in path -- @dg0yt)

### Steps to reproduce
1. Open some file from C:\Dropbox Folder\mymap.omap
2. Do some modifications
3. Save it

### Actual behaviour
A message pops up: "Cannot open file C:\Dropbox Folder\mymap.omap. The process [...]" 

### Expected behaviour
Map should be saved.

### Configuration
Mapper Version: 0.6.8, 0.8.20171231
Operating System: Windows 8.1

**Comment by dg0yt** [comment] 2018-01-02 20:04
Apart from 0.6.8 being somewhat old, I'm unable to reproduce the issue with Mapper 0.6.8 / Windows 7. I have got spaces in most test file paths, and of course in the "symbol set" paths.

Please provide the full error message.

Please check the spelling of the path: On Windows, the separator is backslash, i.e. 
`C:\Users\John Doe\mymap.omap`
Slashes work in many places in Windows but YMMV.

**Comment by bagage** [comment] 2018-01-02 20:28
My bad, first I did an upgrade to the latest unstable version (0.8.20171231) but the issue is still there.

Secondly the issue is not caused by spaces actually, but it is somewhat related to Dropbox. It seems that Mapper creates a temporary file near the real one, then replace it. But Dropbox starts to sync the temp file, and hence I suppose Mapper fails to move the temporary file. Is that some known issue?

I quickly looked for a way of providing logs but couldn't find much (neither in Mapper directly nor in the wiki). Is there a way?

**Comment by dg0yt** [comment] 2018-01-02 20:54
Mapper use [QSaveFile](http://doc.qt.io/qt-5/qsavefile.html#details) for saving maps, and this works exactly by creating a temporary file first, then moving it to the name of the original one.

Search for QSaveFile+Dropbox yields https://bugreports.qt.io/browse/QTBUG-57299 (unresolved). 

I'm reluctant to disable save writing, or provide a global option for this purpose: If Mapper crashes, you would lose your changes. On the other hand, we do have autosave files which we might update just before an unsave write. BTW it is possible to detect Dropbox folders: https://www.dropbox.com/en/help/desktop-web/find-folder-paths, so unsave writing might be disabled selectively.

**Comment by dg0yt** [comment] 2018-02-11 08:28
A fix is proposed for Qt 5.11 (but not integrated yet). This change couldn't be applied directly to Qt 5.6, so I had to leave this open in v0.8.0. Maybe it will be possible to solve this issue with Qt 5.9 / Mapper 0.9.

**Comment by dg0yt** [comment] 2018-04-20 06:39
On https://download.opensuse.org/repositories/home:/dg0yt/Windows/, you will now find 64-bit master builds named `OpenOrienteering-Mapper-master-qt59_...` which use Qt 5.9.5 + [a patch which is to solve the Dropbox issue](https://codereview.qt-project.org/#/c/224800/). Please report back if this solves the problem - even the Qt project is undecided about merging this particular change to the Qt 5.9 Long Term Support branch.

And of course report any new issues which might relate to Qt 5.9 which will become the version used for Mapper 0.9. The `master` branch of Mapper contains only minimal code changes over v0.8.1.

**Comment by dg0yt** [comment] 2018-05-02 06:53
@bagage Did you test, and does it work for you?

**Comment by bagage** [comment] 2018-05-13 19:15
Sorry @dg0yt, I started to test but I felt the bug was still there and did not had time to investigate further. 

Anyway I started again today and this time I can confirm that the bug is gone! Thanks you, this is really a cool bugfix :)

**Comment by dg0yt** [comment] 2019-06-12 07:52
Now with Qt 5.12, it should be also solved for Mapper v0.9.0.

**Closed by dg0yt** 2019-06-12 07:52 UTC
Labels: QTBUG, Windows, known issues v0.7.0, known issues v0.8.0, known issues v0.8.1, known issues v0.8.2
