### ISSUE TITLE
Opening TIFF template - no georeferencing?

### ISSUE THREAD

**Issue by vasyaabr** [OpenOrienteering/mapper#520] opened 2015-10-01 13:50 UTC
While opening TIFF template with georeferencing data, Mapper didn't see this data. "Georeferenced" option in "Open template" dialog is disabled, with text "no georeferencing information". See the TIFF: http://www.windinthehead.org/wp-content/uploads/2015/10/1_modified.tif

**Comment by dg0yt** [comment] 2015-10-02 03:49
This is a GeoTIFF, and reading georeferencing embedded in GeoTIFF is not yet supported (#284).

However, following the instructions from http://www.remotesensing.org/geotiff/faq.html#WorldFile2, I was able to create separate world file from that GeoTIFF. Note that world files do not contain a specificiation of the projection/coordinate referency system. With listgeo -proj4 I could also obtain a custom specification. (UTM seems to work, too.) So with the world file and the projection it is possible to load the TIFF file georeferenced.

Remove .txt from the name of the attached file [1_modified.tfw.txt](https://github.com/OpenOrienteering/mapper/files/6544/1_modified.tfw.txt) if you want to use it, and put in the same directory as the TIFF file. 

Closing this ticket as duplicate of #284.

**Closed by dg0yt** 2015-10-02 03:49 UTC
Labels: duplicate
