### ISSUE TITLE
OpenAerialMap as WMS-based template (tile-based)

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1000] opened 2017-11-05 22:25 UTC
### Expected behaviour
Add possibillity for adding as OpenAerialMap as WMS-based template (similar to how it work in JOSM, Merkaartor, QGIS, etc.) for tracing directly in Mapper.
* https://map.openaerialmap.org/

As all imagery provided by OpenAerialMap licensed under `CC-BY 4.0` license it's possible use it without any "copyright" or "copyleft" limitations on resulted map.
* http://openaerialmap.org/legal/
* https://creativecommons.org/licenses/by/4.0/

### Configuration
Mapper Version: 0.8.x
Operating System: All supported

### REFERENCE
* http://www.gdal.org/frmt_wms.html

**Comment by dg0yt** [comment] 2017-11-05 22:26
Duplicate of #84.

**Closed by dg0yt** 2017-11-05 22:26 UTC
