### ISSUE TITLE
Finishing lines in bezier mode by double tap

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#975] opened 2017-09-27 11:14 UTC
### Steps to reproduce
In the app you can finish a line drawn in beziers either by Finish button or by double tap. This issue concerns the double tap.
The double tap works differently in bezier mode when
1. drawing a straight line 
3. drawing a curved line

### Actual behaviour
1. By doubletapping the line finishes one node before
2.  By doubletapping the line finishes on the position

### Expected behaviour
I would prefer the same action for both - by doubletapping the line finishes one node before.
That way you can see what you have drawn and do not accidentaly bomb the drawn object with more nodes.

### Configuration
Android app 0.7.0

**Comment by lpechacek** [comment] 2017-09-28 06:09
+1

I also observed some inconsistency but I thought that I'm just not yet used enough to Mapper behavior. Now playing with the UI, I can see that in addition of what Aleš described, in straight line mode double click/tap finishes the line at the previous node as opposed to right click which finishes it at cursor position. According to the status line hint right click and double click should behave the same way.

After all it all boils down to double click/tap removing the last segment in straight line mode while all the other methods finish the line at current position. FWIW, I'm in favor of Aleš's expected behavior proposal.

**Comment by dg0yt** [comment] 2017-09-28 06:14
Duplicate of #444 (although with an Android flavour).

**Closed by dg0yt** 2017-09-28 06:14 UTC

**Comment by lpechacek** [comment] 2017-09-28 06:22
Looks like we need a Known Bugs page. <grin>

**Comment by dg0yt** [comment] 2017-09-28 06:25
https://github.com/OpenOrienteering/mapper/issues
