### ISSUE TITLE
Select features by Tag-name

### ISSUE THREAD

**Issue by marcovandersson** [OpenOrienteering/mapper#807] opened 2016-12-03 12:27 UTC
It is about the "select by tag" feature which is very much in help when importing DXF files which holds different geofeatures in different cad-layers. I am always using Karttapullautin (KP) and after an auto-generation the file out2.dxf holds Index, normal and intermediate contours but in different layers/tags. KP also produces a file named dotknoll.dxf with dot knolls and U-depressions. A function for "select all features with the same tag" and then setting the symbol in one click would ease up the process tremendously. Also, much authority data is today "open data" (from EU INSPRIRE Directive), which makes it perfect to add to map as well. This often comes in DXF format as well. 

### Configuration
Mapper Version: 0.6.6
Operating System: Win7 64 (and Ubuntu 14.04 32 bits.)

**Comment by dg0yt** [comment] 2016-12-04 14:18
Duplicate of #358.

**Closed** 2016-12-04 14:18 UTC
Labels: duplicate
