### ISSUE TITLE
Cutting lines

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#977] opened 2017-09-27 12:03 UTC
### Steps to reproduce
There are two ways of cutting line (Scissors button). Either by
1. touching line in different parts and getting segmented line 
2. or by touching and going along a line and getting a "hole" in line

### Actual behaviour
However the touching and holding works well only if started and finished next to a node.
If it starts or finishes on a node the hole does not come to life.

### Expected behaviour
I would like to get holes even when started/ finished on a node.

### Configuration
Android app 0.7.0

**Comment by dg0yt** [comment] 2017-09-28 04:11
Duplicate of #890 which is already marked as a known issue.

**Closed by dg0yt** 2017-09-28 04:11 UTC
