### ISSUE TITLE
Export to PDF - Vector format option is not available

### ISSUE THREAD

**Issue by valdisj** [OpenOrienteering/mapper#1917] opened 2021-03-16 15:43 UTC
MacOS
OO Mapper 0.9.5.
### Steps to reproduce
1. Open OOM file
2. FILE->EXPORT AS
3.Select PFD
4. in OPTIONS select Mode "Vector graphics"
5. Export file
6. Saves as vector PDF file
<img width="389" alt="image" src="https://user-images.githubusercontent.com/5184678/111337114-7c0a8e80-867e-11eb-926c-7ef44700ec7f.png">

### Actual behaviour
1. Open OOM file
2. FILE->EXPORT AS
3.Select PFD
4. in OPTIONS select Mode "Vector graphics" is not available
only Raster graphics is available. No Vector graphics as option

### Expected behaviour
in PDF Export vector mode should work

### Configuration
Mapper Version: 0.9.5
Operating System: MacOS Big Sur 11.2.3 (20D91)

**Comment by dl3sdo** [comment] 2021-03-16 15:53
Duplicate of #1914

**Closed** 2021-03-16 18:17 UTC
Labels: duplicate
