### ISSUE TITLE
Minor issues with dev v20190813.2

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1325] opened 2019-08-14 22:08 UTC
### Issue 1:
1. Opening a geo-referenced file in dev v20190813.2 the gps position is wrong. (Opening the same file in 0.8.4. the gps position is right.)
![2019-08-14-10-36-14](https://user-images.githubusercontent.com/15611653/63059757-8e47a800-bef0-11e9-994f-893b687f71ba.png)
### Issue 2: 
2. Opening a file which was - saved with the option "hide all templates" -  in dev v20190813.2 all files not checked as visible are "not found" and cannot be loaded later. 
![2019-08-14-09-42-53](https://user-images.githubusercontent.com/15611653/63059767-94d61f80-bef0-11e9-8a8f-0a7d96863f7b.png)
### Configuration
Mapper Version: dev v20190813.2
Operating System: Android 4

**Comment by dg0yt** [comment] 2019-08-15 04:26
> Opening a geo-referenced file in dev v20190813.2 the gps position is wrong. (Opening the same file in 0.8.4. the gps position is right.)

Which was the georeferencing and (approximate) actual position in this moment? Now using PROJ library version 6, things could get *more accurate*, but we might still be using the library wrongly with regard to some CRS.

> Opening a file which was - saved with the option "hide all templates" - in dev v20190813.2 all files not checked as visible are "not found" and cannot be loaded later.

I could not reproduce this on the desktop now. Are the "lost" templates stored in the same directory tree or type of storage? Mapper asks for permissions a little bit later now, and if it doesn't need to ask for the map, it won't have the permissions for the tempates later.

**Comment by dg0yt** [comment] 2019-08-15 04:39
> > Opening a file which was - saved with the option "hide all templates" - in dev v20190813.2 all files not checked as visible are "not found" and cannot be loaded later.
> 
> I could not reproduce this on the desktop now.

And also not on Android 4.4 where permissions are always granted in advance

**Comment by lpechacek** [comment] 2019-08-15 06:11
> Issue 2:

>    Opening a file which was - saved with the option "hide all templates" - in dev v20190813.2 all 
> files not checked as visible are "not found" and cannot be loaded later.

I also face this bug. The workaround is to make all templates visible before moving the map file to Android device (Android 7). In reverse direction when I open file saved on Android tablet on the desktop version, templates cannot be found again. However, after saving the file on desktop and opening it again makes templates appear. I'm using the `OOMapper` location on internal storage for map files.

**Comment by dg0yt** [comment] 2019-08-15 06:12
I see. There is some tricky code around handling absolute and relative paths.

**Comment by dg0yt** [comment] 2019-08-15 17:20
> > Issue 2:
> 
> > Opening a file which was - saved with the option "hide all templates" - in dev v20190813.2 all
> > files not checked as visible are "not found" and cannot be loaded later.
> 
> I also face this bug. The workaround is to make all templates visible before moving the map file to Android device (Android 7). In reverse direction when I open file saved on Android tablet on the desktop version, templates cannot be found again. However, after saving the file on desktop and opening it again makes templates appear. I'm using the `OOMapper` location on internal storage for map files.

I can reproduce this bug on Android. However I do not need to go back to the desktop: Uncheck "Hide all templates", save, close, and open again - that is enough to workaround the bug.

**Comment by dg0yt** [comment] 2019-08-27 06:03
> Which was the georeferencing and (approximate) actual position in this moment? Now using PROJ library version 6, things could get more accurate, but we might still be using the library wrongly with regard to some CRS.

@mlerjen Any news?

**Comment by mlerjen** [comment] 2019-08-27 07:53
@dg0yt: as shown in the first figure. GPS Position  approx. 145m away from the actual position. (Working with geo-referenced basemaps in EPSG 2056)

**Comment by dg0yt** [comment] 2019-08-29 07:00
> GPS Position approx. 145m away from the actual position.

Is the recorded GPX data shifted, too?

**Comment by dg0yt** [comment] 2019-08-29 07:49
I created an EPSG 2056 test file in v0.8.4, and compared with `dev`: There is a difference in projection.

| Mapper | v0.8.4 | dev |
|---------|------|-------|
| PROJ version | 4.x | 6.x |
| Projected | 2643093 1150008 | 2643093 1150008
| Geographic | 46.5° 8.0° | 46,501262° 8,001029°

I didn't check the details so far. Which version is right?


[#1325 GPS offset EPSG 2056.zip](https://github.com/OpenOrienteering/mapper/files/3554422/1325.GPS.offset.EPSG.2056.zip)

**Comment by mlerjen** [comment] 2019-08-29 09:30
![image](https://user-images.githubusercontent.com/15611653/63928590-1a5ce200-ca50-11e9-9ba2-9d5f4f9202f4.png)
![image](https://user-images.githubusercontent.com/15611653/63928656-39f40a80-ca50-11e9-8403-e9f3946af00a.png)
According to map.geo.admin.ch the .proj 4.x version is right. But 6.x ends up with an offset of about 155m

**Comment by mlerjen** [comment] 2019-08-30 09:41
Test: 
1) Open EPSG 2056 map with v0.8.4.
2) Walk around the block with GPS recording on.
(checking with the basemap, GPS Position and Basemap agree)
3) Save map. Open map with dev v20190813.2
4) Do the same walk record GPS.
(basemap  and GPS do not agree).
5) Save map. Re-open with v0.8.4. 
![2019-08-30-11-25-26](https://user-images.githubusercontent.com/15611653/64010567-52305c00-cb1a-11e9-85a4-aae799311a6d.png)
6) Save map. Re-open with dev2019...
![2019-08-30-11-24-26](https://user-images.githubusercontent.com/15611653/64010579-578da680-cb1a-11e9-8d12-95fa65e0030a.png)

Result: Both recorded GPS tracks are consistent, but only the base map accords to the GPS tracks. Offset of the dev basemap is around 180m.

**Comment by krticka** [comment] 2019-08-31 09:04
I was thinking that this problem (issue 2) can be related to translation between WGS84 and Bessel ellipsoid but it works OK for our national CRS which is also using Bessel (EPSG 5514). Both 0.8.4 and dev are OK. Probably related only to CH1903+/LV95.

**Comment by dg0yt** [comment] 2019-08-31 15:56
It is a little bit unclear why there is a behavioural difference for this particular CRS. We are still using the old application programming interface (API) from PROJ 4. When using the PROJ 6 command line programs, which use the new programming interface, you may normally see the expected results - unless you add `+no_defs`. It is neither trivial to identify the right changes for using the old interface nor to port Mapper to the new interface.

I added EPSG:2056, projection center (Bern) to our unit tests. I made some progress on using the new API (GH-1341), based on work from @pkturner (GH-1218). Now EPSG:2056 Bern passes. However, the tests with the Potsdam datum fail with the new APIs (to be fixed by https://github.com/OSGeo/PROJ/pull/1573...).

Apart from a fix for the Potsdam bug, these changes require at least PROJ 6.1. I still need to find out how it will eventually work on PROJ versions 5.0 to 6.0 (as used by some Linux distributions).

**Comment by dg0yt** [comment] 2019-09-16 04:23
The updated GeoreferencingTest (incl. EPSG 2056) passes on Ubuntu 18.10 which has PROJ 5.1.

The old PROJ API is still used with PROJ 6.0, but our [target systems page](https://github.com/OpenOrienteering/mapper/wiki/Target-systems) doesn't list any Linux distribution using this version.

**Closed by dg0yt** 2019-09-16 04:23 UTC
Labels: known issues unstable
