### ISSUE TITLE
ocd export doesnt support spot colors

### ISSUE THREAD

**Issue by FEK10** [OpenOrienteering/mapper#689] opened 2016-06-07 14:24 UTC
why is there still not spot color support for 
ocad files in openorienteering mapper

**Comment by dg0yt** [comment] 2016-06-08 04:18
The question is easy to answer: There is 221 open issues, probably the same number of issues and ideas not tracked online, and only one person working on Mapper in his precious free time. Apart from this, the OCD export need a rewrite. (The OCD import was rewritten some time ago, in order to support a broad range of OCD versions.)

According to the title, this is a duplicate of #205.

**Closed by dg0yt** 2016-06-08 04:18 UTC
Labels: duplicate
