### ISSUE TITLE
Importing .shp (shape-files)

### ISSUE THREAD

**Issue by soeby** [OpenOrienteering/mapper#573] opened 2015-12-28 15:01 UTC
I missing the function to import shape-files. I have tried converting shape-files to .dxf via QGIS, but OOM don't accept the converted file. 
All maps in Denmark are based on data from Danish Geodata Agency, which only provides map data in the formats: SHP, TAB, MDB and GML.

Thanks.

**Comment by dg0yt** [comment] 2015-12-30 18:40
Duplicate of #171. You may subscribe there.

Needs #574.

**Closed by dg0yt** 2015-12-30 18:40 UTC
Labels: duplicate

**Comment by gudeso23** [comment] 2018-07-31 05:10
Is this issue fixed? Can I add shp layer in version 0.81 and if so how?

**Comment by dg0yt** [comment] 2018-07-31 05:25
@gudeso23 According to #171, this was done in v0.7.0, in April 2017.

**Comment by gudeso23** [comment] 2018-07-31 06:56
Any instruction on how to import shp files? I recall I had issues in the past

**Comment by dg0yt** [comment] 2018-07-31 11:15
@gudeso23 
a) It doesn't need special instructions: Load SHP files as templates, or import them into a map via File > Import... 
b) Please stop asking in this issue, as the original poster will receive notifications every time.
c) Please try to read the manual first. If you want to report unexpected behaviour (feature requests), please be as specific as possible.
