### ISSUE TITLE
Can we use Mapper on ios devices?

### ISSUE THREAD

**Issue by AhmetPolat43** [OpenOrienteering/mapper#1798] opened 2020-12-14 16:58 UTC
Can we use Mapper on ios devices?

**Comment by Symbian9** [comment] 2020-12-14 18:53
Duplicate of https://github.com/OpenOrienteering/mapper/issues/1509

TL;DR:  It may be possible to build OpenOrienteering Mapper for iOS, with additional modifications.

But OpenOrienteering Team actually has no plans to provide builds for iOS (iPhone/iPad) devices.

**Comment by lpechacek** [comment] 2020-12-14 18:58
> But OpenOrienteering Team actually has no plans to provide builds for iOS (iPhone/iPad) devices.

Don't get discouraged by the answer. Mapper is opensource. Feel free to port the program to iOS and contribute the integration bits.

**Closed by lpechacek** 2020-12-14 18:58 UTC

**Comment by dg0yt** [comment] 2020-12-14 19:08
Just note that is currently not possible to distribute iOS app in Apple's official way.
