### ISSUE TITLE
Direct import of LiDAR data?

### ISSUE THREAD

**Issue by MartinHore** [OpenOrienteering/mapper#1758] opened 2020-10-21 12:27 UTC
### Steps to reproduce
1. I'm currently processing UK govt. LiDAR data in SAGA-GIS. From DTM and DSM data I can output heat maps of ground altitude and tree height which I can open as templates in OOM. Also contour shapefiles which I can import direct into the map or open as templates. To process Point Clouds to estimate vegetation density I'm using LAStools and Kartapullautin. Is OOM likely to include direct reading of LiDAR data in future updates? (Or has it already happened and I've missed it?). If not, I'm very happy to share my methods or to learn from others who may have better solutions. I'm currently using OOM version 9.3. Many thanks, and sorry if this has already been covered in another topic - I couldn't find it I'm afraid.
2.
3.

### Actual behaviour
Tell us what happens

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version:
Operating System:

**Comment by dg0yt** [comment] 2020-10-23 04:39
LiDAR processing is not a feature yet. Unlike the recent "contouring" question (GH-1751), this can't be achieved with the current components (GDAL) alone. However, open source C++ libraries and tools exist for point cloud data (in particular [PDAL](https://pdal.io/)).

**Comment by Symbian9** [comment] 2021-01-15 03:35
Guess, actual issue is duplicate of https://github.com/OpenOrienteering/mapper/issues/915

> However, open source C++ libraries and tools exist for point cloud data (in particular [PDAL](https://pdal.io)).

Good news!

**Comment by MartinHore** [comment] 2021-01-15 17:23
I've just been notified by email that this topic had another comment today.

I've now progressed a lot further with processing LiDAR data in SAGA-GIS to produce templates for use in OOM. I'm currently completing writing up my notes on this - they should be finished in a couple of weeks. As well as contours, I've generated templates that display hillshade , slope gradient, vegetation height and undergrowth density. I've also used SAGA-GIS to undertake a coordinate transformation to the UK "OSGB 36" national grid for aerial photographs from SASPlanet, and to merge, crop and/or geo-referernce map tiles from UK OS OpenData and other sources. I only use software with user-friendly interfaces - I'm not a programmer.

This pretty much duplicates what OCAD 2018 achieves, with a lot of scope for personalisation, but of course OCAD does the job with considerably less effort. It's been an interesting and enjoyable task, particularly in these COVID times, though one which will become redundant if OOM develops a LiDAR processing facility to match OCAD. Until then I'm very happy to share freely the methods I use with other OOM users, and to learn from others as well of course.  Some of my notes may be published on the British Orienteering website in due course, but I'm also happy to share direct. Some of the methods I use are UK specific, but should be adaptable for non-UK users, depending on the LiDAR formats other mappers have available.

Martin

**Comment by dg0yt** [comment] 2021-01-15 17:53
Martin, thank you very much for your comment. You are welcome to share your information in the new "Show and tell" discussions area at 
https://github.com/OpenOrienteering/mapper/discussions/categories/show-and-tell

I will close this issue here as a duplicate of #915. You can also subscribe there for future updates.

**Closed by dg0yt** 2021-01-15 17:53 UTC
