### ISSUE TITLE
Select by tag

### ISSUE THREAD

**Issue by jan-gerard** [OpenOrienteering/mapper#631] opened 2016-03-22 09:34 UTC
Tags are a nice feature. But I would like to be able to select by tag value (maybe using wildcards or regular expressions).

And it would be convenient to be able to set the tag of multiple selected objects at once. Now, when I select multiple objects and edit a tag, only one of the selected objects' tag value is modified.

**Comment by dg0yt** [comment] 2016-03-22 19:46
Duplicate of #358. 

A search dialog could be a first step in that direction.

**Closed by dg0yt** 2016-03-22 19:46 UTC
