### ISSUE TITLE
Vectorize raster template in Mapper

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#833] opened 2017-01-31 08:56 UTC
Here is example code, that could be integrated inside Mapper (Qt5-based, licensed under GPLv3)
* https://github.com/lpechacek/cove

### Expected behaviour
Add possibility for vectorizing raster templates directly in OOM and paste resulted curves in current map (map part).

### Configuration
Mapper Version: 0.6.x and above
Operating System: All supported

**Comment by lpechacek** [comment] 2017-02-22 15:23
A prototype implementation is at https://github.com/lpechacek/mapper/commits/cove_rfc. Packages will be at http://download.opensuse.org/repositories/home:/LPechacek:/branches:/home:/dg0yt:/staging/ once I get the build working.

**Comment by Symbian9** [comment] 2017-02-22 18:11
@lpechacek, good job!

**Comment by Zerbembasqwibo** [comment] 2017-03-01 06:20
I tried the Windows version on Windows 7 64 bit.

It worked VERY well, I could quickly digitize an old map (let's not talk about the result though...).

It crashed once when I tried to change background map. It was a map I added after opening the program. I didn't try to reproduce it.

Otherwise: 
- A bit strange %-scales, it seemed all picture processing started at approc 75% done?
- The thinning of line was very slow, difficult algorith I suppose
- missed a "cancel button" when ready with picture/vector analysis
- Zoom also? 

I "tried this at home" before and marshes are very difficult since they destroy colors. I think anyway that with good knowledge of how to manipulate the picture before vecorizing you can get amizing good results! I am very happy for this branch since I am up to digitize old paper maps.

**Comment by lpechacek** [comment] 2017-03-01 14:25
@Zerbembasqwibo, thanks for the encouraging feedback. I'd be happy to learn about the crash if you manage to replicate it.

Ad the progress bars, the line vectorization tool spawns QProgressDialog for every time consuming operation. However, Qt seems to withhold displaying it for a few seconds. Looking into the issue is on my list.

Thinning should not be slow. The algorithm is optimized and was reasonably fast even on the 166 MHz Pentium which ran the first version of this software. There are, however, problems with refreshing the B/W image window content after the operation completes. Moving the image or resizing the dialog window makes Qt repaint the face. This defect is on my list too.

Not sure about the "cancel button" note. Can you be more specific, please?

Zoom can be accessed via a context menu in the image view window. Also mouse wheel and Ctrl + mouse pointer drag work.

Regarding scanned maps with overprint, higher number of color classes (15) and repeated learning/color classification attempts help. Getting good results is usually subject to experimenting and I don't have enough experience in this area yet to provide solid guidance.

**Comment by dg0yt** [comment] 2017-03-02 06:49
Regarding the progress dialog: You will need to ```setMinimumDuration(0)```, and you will have to call ```QApplication::processEvents()```when updating the progress without return to the event loop. We have a similar situation with printing (https://github.com/OpenOrienteering/mapper/blob/master/src/gui/print_progress_dialog.cpp), including Cancel button.

**Comment by Zerbembasqwibo** [comment] 2017-03-02 08:08
Thanks, zoom works fine.

15 colors and use 2 for vectorize, I used just default and used not even
all buttons, useful result I would say. I guess even better will be easy to
get if yuo spend time on it.

https://pbs.twimg.com/media/C55ffxtWUAAiYGc.jpg

Cancel: the box "Contour vectorizer" doesn't have a cancel / OK button, use
only the upper right cross for closing the box.

Q: Areas possible to vectorize, the name of the box indivates otherwise?



2017-03-01 15:25 GMT+01:00 Libor Pecháček <notifications@github.com>:

**Comment by lpechacek** [comment] 2017-03-02 16:57
@dg0yt, thanks for the hint. The progress bars pop up unconditionally now.

@Zerbembasqwibo, is the image you are referencing a result of the line tracing? If that's the case, can you ahre the scanned template?

Ad area tracing, I deem it possible modulo patterned ones. However, areas in orienteering maps are not that numerous as lines and I currently don't consider implementing this functionality.

**Comment by Zerbembasqwibo** [comment] 2017-03-02 22:48
@lpechacek Here is a picture of the scanned map.

https://pbs.twimg.com/media/C58p0vdXEAA6cxr.jpg:large

Area: OK, I understand.

**Comment by dg0yt** [comment] 2017-03-10 08:14
I could merge/reimplement the build system parts which optionally add 3rd-party/cove (which I would add later).
However, I would add the trigger for this feature to the per-template actions gear of raster templates, similar to the import-and-remove action for vector templates. In this way, there is no need to select a template in the cove code.

**Comment by lpechacek** [comment] 2017-03-10 10:07
I like the plan.

Please note that I consider CoVe still alpha level. Among others I'll drop polygon transformation into Bezier curves (duplicates Mapper functionality) and mitigate the dependency on Qt XML module before requesting integration. We should also briefly discuss the code maintenance cooperation model.

**Comment by dg0yt** [comment] 2017-03-10 15:47
The short term plan is to isolate your playground (3rd-party/cove in your fork) from the parts of Mapper which I am modifying at the moment (buildsystem in the first place). On OBS I could easily extract 3rd-party/cove from a separate tarball when we are ready to enable it in the unstable build.

In the long term, I would prefer to maintain at least the UI as part of Mapper, for consistency, translation etc. It could still be a quite separate component, similiar to how GDAL is handled. But I didn't study the code enough to know if this feasible, and I don't know your plans how much you want to maintain cove as a standalone tool.

**Comment by Symbian9** [comment] 2017-08-13 15:03
@lpechacek, any news?

Are there working 'unstable' with this feature availiable for testing?

**Comment by lpechacek** [comment] 2017-08-22 14:32
Unstable packages based on Mapper 0.7.0 are available at download.opensuse.org (see above). Progress is slow but constant. ;)  CoVe is undergoing slimming as some features duplicate Mapper functionality. The goal is to trim it down to a stable core that does line tracing right. Of course usage documentation must be added unless someone develops a "wizzard" mode. Contributions are welcome.

**Comment by Symbian9** [comment] 2018-08-07 21:16
@lpechacek, any news on development CoVe?

**Comment by lpechacek** [comment] 2018-08-10 12:00
Yes. Code base modernization is progressing and you can watch it on https://github.com/lpechacek/mapper/commits/cove_rfc. However, I considered OCD file import and export more important topic so vectorization was lower priority in past months.

If there is enough interest in testing, I can provide updated packages and instructions how to use the tool.

**Comment by Symbian9** [comment] 2018-08-10 13:04
@lpechacek, yes, I would be happy to test it!

If you can, provide package for Debian 9.x stretch.

**Comment by Zerbembasqwibo** [comment] 2018-08-10 13:40
I use an old version at it works quite ok. Problem is that it's too many
alternatives in the process: I cannot figure out how to receive best
result. Probably lot's of testing can give suggestipns on how to improve
the tool so it's easier for the user.

The mix of contours and open marshes is the most difficult I guess.

fredag 10 augusti 2018 skrev app4soft <notifications@github.com>:

**Comment by lpechacek** [comment] 2018-08-29 11:05
Updated packages are at https://download.opensuse.org/repositories/home:/LPechacek:/branches:/home:/dg0yt:/staging/

Quick how to:
1) Load a raster template into Mapper, make sure it is visible. It is recommended to create a new part for the vectorized lines as they need clean up and symbol assignment.
2) Under template Edit button (at the bottom of the template setup dialog) choose "Vectorize lines"
3) Vectorizer tool starts, presenting the image in 1:1 scale. You can pan and zoom the image. If there is color noise in the picture, due to scanning from paper, apply FIR filter (in the bottom right corner of the window).
4) Switch to Colors tab and perform color classification. The tool reduces image color space into predefined number of buckets to separate differently colored features. For single color images like contour lines from WMS (yes, in my country it is possible to get them), leave the default number of two color buckets. Full color maps digitally generated directly from source 12-15 buckets may be needed. Maps scanned from paper, especially those with overprint will require 15-20 buckets.
5) After color classification finishes, select buttons which correspond to the colors of the features you want to vectorize. The features will be highlighted in red. If the features "bleed" into surrounding ones, try running classification once more (it is a stochastic process) or try increasing the number of buckets. Pre-defining colors found in the picture in the Initial colors dialog may also help.
6) Once you are happy with the separation, proceed to Thinning. In this step there are  modifications done to the final black-and-white image. If the lines you want to vectorize are too thin and occasionally broken with small gaps, you may consider applying Dilate operation on them. It will fix small gaps in lines making the continuous. However, if some of the lines are too close (steep hills), these lines will be melted together.
7) The final steps in vectorization are line thinning and the actual vectorization process. Without thinning any feature thicker than one pixel will not be considered for vectorization. Resulting vector lines appear in cyan color overlaid over the image. Clicking Save vectors transfers the resulting lines into currently selected map part.
8) After closing the vectorizer tool window you are back in Mapper. All vectorized lines are selected and can be removed with either Undo or Delete. All the lines carry tag "name=cove", are composed of straight lines and have no symbol assigned.

Further steps: Assign the lines their symbols. You can vectorize not only contour lines but also paths and any line object in general. Join/split lines as needed, remove artifacts. Convert lines to curves and possibly also simplify them. Vectorized lines can be looked up in the map using Find object tool with query "name=cove".

I'd be happy for any volunteer willing to morph the above how to into a proper manual with screenshots, recommendations and full functionality description.

**Comment by Symbian9** [comment] 2018-08-29 13:49
> Updated packages are at https://download.opensuse.org/repositories/home:/LPechacek:/branches:/home:/dg0yt:/staging/

Great! Will test it today ;-)

NOTE: Please, set custom package name, something like `openorienteering-mapper-cove` that will give possibility to install it on side-by-side with [official packages produced by dg0yt](https://download.opensuse.org/repositories/home:/dg0yt/) (i.e. `openorienteering-mapper`, `openorienteering-mapper-master` and `openorienteering-mapper-unstable`)

**Comment by Symbian9** [comment] 2018-09-22 23:38
OK, I just tested `openorienteering-mapper-cove_0.8.2.996` -- awesome work, @lpechacek!

- https://download.opensuse.org/repositories/home:/LPechacek:/branches:/home:/dg0yt:/staging/Debian_9.0/amd64/openorienteering-mapper-cove_0.8.2.996_amd64.deb
- https://www.openorienteering.org/assets/openorienteering/contour_bg.gif

![cove test](http://i.imgur.com/PKZlDAh.png)

Found few small issues on interface labels, but it mostly usable already. ;-)

Also, I started working on "morph the above how to into a proper manual with screenshots, recommendations and full functionality description" (think, need week or two to finish it)

![cove faq](http://i.imgur.com/UG51UOR.png)

**Comment by lpechacek** [comment] 2018-09-23 08:01
Cool! Thanks for testing and starting work on the howto!

**Comment by Symbian9** [comment] 2019-01-18 23:38
@lpechacek, any news about *COVE*? 

FTR, here is in detail description of the *OCAD TPI* based contour generalization procedure:

- https://www.linkedin.com/pulse/way-fully-automatic-generation-contour-lines-highest-demands-gloor

**Comment by lpechacek** [comment] 2019-01-21 10:19
> @lpechacek, any news about COVE?

I'm maintaining CoVe enabled packages in the aforementioned repository. The packages are currently at v0.8.4 and "just work". @dg0yt what do you think about merging CoVe into Mapper in an "experimental/staging" manner. The code is not all beauty but it's obviously useful for some users.

> FTR, here is in detail description of the OCAD TPI based contour generalization procedure:
>     https://www.linkedin.com/pulse/way-fully-automatic-generation-contour-lines-highest-demands-gloor

The recent OCAD enhancement is unrelated to CoVe operation. OCAD applies smoothing to the digital elevation model. CoVe just extracts and interpolates selected lines from a bitmap.

BTW, I've recently generated similarly smooth contour lines from DEM using QGIS 3 with help of [FFT Convolution filter plugin](https://github.com/lpechacek/fft-convolution-filter).

Contour lines from DEM before smoothing, interval 5m:
![image](https://user-images.githubusercontent.com/5584406/51467340-a09fa000-1d6c-11e9-9c7e-6b03b1a1192f.png)

After smoothing the DEM with kernel of 25m radius:
![image](https://user-images.githubusercontent.com/5584406/51467399-c2992280-1d6c-11e9-86b1-cfb8babfabe5.png)

OCAD's enhancement Gaussian filter with TPI index weighting is a very clever idea and surely gives better results than the above example.

I'm wondering what is @dg0yt's stance on enhancing Mapper with functionality like WMS or DEM processing. I know there is a ticket for WMS and GDAL can be persuaded to do the job for Mapper. On the other hand QGIS already has the necessary WMS and DEM processing functions and Mapper can leverage it by referencing the existing tool in its documentation.

**Comment by Symbian9** [comment] 2019-01-21 15:40
@lpechacek , there was *ContourTrace* app as part of *OpenOrienteering* project, but it abandoned many years ago

- https://www.openorienteering.org/apps/contourtrace/

As I remember, there was idea on adding DEM import into *ContourTrace*.

About WMS — it reqested since 2012

- https://github.com/OpenOrienteering/mapper/issues/84

**Comment by Symbian9** [comment] 2019-01-30 16:55
@lpechacek , near forget that *OpenOrienteering* also has *LaserScan Tool* for processing LiDAR data

- https://www.openorienteering.org/apps/laserscan-tool/

**Comment by lpechacek** [comment] 2019-01-31 07:57
@Symbian9, good point about _ContourTrace_.

**Comment by dg0yt** [comment] 2019-01-31 08:02
> what do you think about merging CoVe into Mapper in an "experimental/staging" manner. The code is not all beauty but it's obviously useful for some users.
- I would merge that in `dev`.
- I'm a little bit reluctant with regard to duplicate identifiers such as `MapColor`
- I would appreciate the possibility to use an external potrace, as provided by Linux distributions. I would put this package in the Superbuild repository.
- Copyright and licensing must be clearly document, for all files. (I'm using and maintaining debian copyright files.)

I think the next steps somewhat depend on how much you want to continue to maintain it as a separate tool. (We might build it as a separate program within the Mapper package.) People will report bugs, and we may face build issues. So we have to know where this project has its home.

> I'm wondering what is @dg0yt's stance on enhancing Mapper with functionality like WMS or DEM processing. I know there is a ticket for WMS and GDAL can be persuaded to do the job for Mapper. On the other hand QGIS already has the necessary WMS and DEM processing functions and Mapper can leverage it by referencing the existing tool in its documentation.

Mapper (desktop) appeals most to novice and occasional users ATM. From my impression, they need simple tools and good documentation. There is much room for improvement with our documentation (let alone translation), but QGIS is probably too hard for many of these users. With GDAL, we have many of the features already quite close.

However, I wonder where is the best place to put all these *data tools* in our desktop menu. (I don't even know where to place GPX recording.) A "data" menu? An "extra" menu?

**Comment by dg0yt** [comment] 2019-01-31 08:05
@Symbian9 wrote:
> Also, I started working on "morphing the above how to into a proper manual with screenshots, recommendations and full functionality description" (think, need week or two to finish it)

Any news?

**Comment by Zerbembasqwibo** [comment] 2019-01-31 08:06
"Advanced" menu?

torsdag 31 januari 2019 skrev Kai Pastor <notifications@github.com>:

**Comment by Symbian9** [comment] 2019-01-31 08:55
> "Advanced" menu?

Or "GIS Tools", as GIS -- is advanced mapping.

**Comment by Zerbembasqwibo** [comment] 2019-01-31 10:22
"GIS tool" is good.

torsdag 31 januari 2019 skrev app4soft <notifications@github.com>:

**Comment by jmacura** [comment] 2019-01-31 18:07
> as GIS -- is advanced mapping.

It certainly isn't.
And I don't believe that an unknown acronym will causes a _"novice and occasional users"_ to use such tools, also unknown to them, and not to run away screamingly.
I believe "Data tools" describes it quite well already.

**Comment by Symbian9** [comment] 2019-01-31 19:35
> I believe "Data tools" describes it quite well
already.

Then -- "GIS data".

**Comment by lpechacek** [comment] 2019-02-01 14:52
Gentlement, would you mind moving the extended GIS discussion to corresponding tickets? We do have a WMS one, there is another for laser scan tools and in addition there is the ideas incubator. Thanks for your understanding.

**Comment by Symbian9** [comment] 2019-08-15 23:35
@lpechacek what you think about implementing *PolyVectorization
* into `cove`?

- https://github.com/bmpix/PolyVectorization

**Comment by lpechacek** [comment] 2019-12-19 09:51
@Symbian9, yes, it seems to make sense. I've created GH-1466 for tracking. Thanks for the suggestion!

**Comment by lpechacek** [comment] 2019-12-19 10:02
> I would appreciate the possibility to use an external potrace, as provided by Linux distributions. I 
> would put this package in the Superbuild repository.

@dg0yt, potrace code had to be modified for tracing open paths. Refer to https://github.com/lpechacek/mapper/blob/cove/3rd-party/cove/potrace/potrace-1.6.diff for the modifications made. In my opinion, it makes more sense to rewrite Potrace's `trace.c` into C++ and merge it into CoVe, rather than push the above changes into mainline Potrace. Replacing Potrace with another implementation would be also an alternative.

**Comment by dg0yt** [comment] 2019-12-20 07:32
> potrace code had to be modified for tracing open paths. Refer to https://github.com/lpechacek/mapper/blob/cove/3rd-party/cove/potrace/potrace-1.6.diff for the modifications made. In my opinion, it makes more sense to rewrite Potrace's `trace.c` into C++ and merge it into CoVe, rather than push the above changes into mainline Potrace. Replacing Potrace with another implementation would be also an alternative.

I'm fine with local modifications. What I did for Qt printsupport (and recently started for QBezier), is adding the pristine code to a separate branch in this repository (for integration of future upstream changes), and do modifications in a separate branch (which may occassionally merge the pristine branch).
- https://github.com/OpenOrienteering/mapper/tree/printsupport-qt
- https://github.com/OpenOrienteering/mapper/tree/printsupport-mapper

In this way, you have upstream and the local fork properly mapped to git branches, with all features of git for logs, diffs, etc.

**Closed** 2019-12-20 08:35 UTC
Labels: enhancement
