### ISSUE TITLE
Crash while closing template adjustment window

### ISSUE THREAD

**Issue by aivarszo** [OpenOrienteering/mapper#1707] opened 2020-08-25 08:37 UTC
### Steps to reproduce
1. Open map with or without template
2. Activate Template Setup window
3. Select template and activate Template Adjustment window
4. Close Template Adjustment window.

### Actual behaviour
Mapper crashes in irregular manner - not always, but more often then normal operation.

### Expected behaviour
Should not crash.

### Configuration
Mapper Version:
0.9.3
Operating System:
MacOS 10.15.6
Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	2,6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB

**Comment by dg0yt** [comment] 2020-08-25 08:55
Duplicate of GH-1690.

**Closed by dg0yt** 2020-08-25 08:55 UTC
