### ISSUE TITLE
Different handling of "out-of-print area" case 

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#812] opened 2016-12-12 15:19 UTC
### Steps to reproduce
1. Open a new map
2. Geo-reference the map with EPSG code 2056 (new Swiss Reference System)
3. Import geo-referenced template
4. show whole map
3. Draw geo-referenced objects. Save. Close.
4. Re-open Map project: Getting message: Some objects are outside the print area and therefore deleted.
5. All drawn objects are gone.

### Actual behavior
By defining the reference system via EPSG  the geographic coordinates of the reference point get set to the reference point of the coordinate system. In case of the new Swiss coordinate system this point is western of the Portuguese island of Madeira...  A terrain situated in Switzerland still can be drawn and saved but not be re-opened anymore, without total loss of the map content.

### Expected behavior
-> At some point Mapper shall test for objects out of printing area and if possible suggest an adjustment of the reference point (for ex. to center of the drawn area).
-> Alternatively this can also happen at the opening replacing the  blunt deleting the out of print area content.

### Configuration
Mapper Version: 0.6.5.
Operating System: Windows 7

**Comment by dg0yt** [comment] 2016-12-12 19:58
My first guess is that this is a duplicate of #806. Actually just a single wrong letter.

**Comment by mlerjen** [comment] 2016-12-13 07:15
I can confirm that. My case was just more fatal :-)

> Some coordinates were out of bounds for printing. Map content was adjusted.
> Dropped one irregular object.

Testing with the unstable 0.6.20161212 I confirm the issue is solved.

> Some coordinates were out of bounds for printing. Map content was adjusted.

**Closed** 2016-12-13 07:16 UTC
