### ISSUE TITLE
Cut Object tool crashing on Linux (Pop OS 20.04)

### ISSUE THREAD

**Issue by cmorse01** [OpenOrienteering/mapper#1634] opened 2020-05-21 01:44 UTC
### Steps to reproduce
1. When using the cut object tool (right click, tool bar or 'K' key) causes my system to immediately close all programs and log out.  System 76 laptop with NVidia RTX 2070 graphics card - dual monitors.  System fully stable with all other tools and under load with other applications.  Just this tool that causes the crash.
2. If I switch to internal graphics chip (Intel UHD Graphics 630 but lose the dual monitor support), cutting object doesn't crash the system, but the scissor mouse icon is very glitchy and 4x the size of other icons.  Icon only displays when moving mouse (which likely explains glitchiness) when I stop moving mouse, icon disappears completely, reappears when mouse moved.  Otherwise I would have provided a screenshot.
3. This behaviour happened a couple times, but not consistently on 0.9.2, now with upgrade to 0.9.3 it happens every time I try to cut an object (contour, path etc).

### Actual behaviour
Tell us what happens

### Expected behaviour
Tell us what should happen instead

### Configuration
Mapper Version: 0.9.3 linux
Operating System: Pop! OS 20.04 LTS, 5.4.0-7629-generic kernel (all updates applied), GNOME desktop environment.

**Comment by dg0yt** [comment] 2020-05-21 03:50
Which Mapper binaries do you use? 

> Operating System: Pop! OS 20.04 LTS

I assume this is some Ubuntu 20.04 derivative. Still, it may use a different build of Qt, or add some special platform plugin.

> System fully stable with all other tools and under load with other applications.

Does this include Qt and KDE applications, e.g. Krita?

**Comment by dg0yt** [comment] 2020-05-21 04:06
> This behaviour happened a couple times, but not consistently on 0.9.2, now with upgrade to 0.9.3 it happens every time I try to cut an object (contour, path etc).

Didn't you actually use 0.9.2 with a version of Pop! OS other than 20.04 LTS?

**Comment by cmorse01** [comment] 2020-05-21 12:19
Pop! OS is indeed a Ubuntu derivative.  I'm using the binaries from the APT repository

I upgraded to 20.04 a few weeks back so there were a few weeks running 0.9.2 on 20.04 with only an intermittent glitch.  But since upgrading to 0.9.3 it happens every time without fail. I don't recall if the glitch occurred on 19.10 or not.  This is a new machine since late March, previously I was running under Ubuntu MATE on a different machine.  (Which has since been repurposed to Windows for PurplePen, so I can't go back and test on that machine unfortunately).

Let me see if I can find out what Qt build is currently.

![Screenshot from 2020-05-21 08-11-14](https://user-images.githubusercontent.com/18015793/82557965-b4af0980-9b3a-11ea-844e-30385e9d916e.png)

**Comment by cmorse01** [comment] 2020-05-21 12:21
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu

**Comment by cmorse01** [comment] 2020-05-21 12:26
Another aspect of this behavior I noted after posting last night is that once my system has force-logged me out due to the Cut Object glitch, if I simply relog into my session, the system will randomly log out in the same fashion, even if not actively using OOM.  However, if I do a reboot before logging back in, system remains stable until I cut object again.  So it appears some system parameter might be getting corrupted that a full reboot resolves.

**Comment by dg0yt** [comment] 2020-05-21 14:11
I suppose the cause is completely unrelated to Mapper, but merely more reliably triggered by it.

Can you please run `qtdiag`? Among other things, it will display theme/platform/style related parameters, and I would like you to run Mapper with Pop!_OS additions.

**Comment by dg0yt** [comment] 2020-05-21 14:14
(And then the next step would be building Mapper from source. After all, it has a lot of dependencies via Qt and GDAL, so this a large front for subtle cross-platform incompatibilities. Given the source package, building from source is not too hard. It will just eat disk space for development packages.)

**Comment by cmorse01** [comment] 2020-05-21 16:54
Output of qtdiag - 

Qt 5.12.8 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.3.0) on "xcb" 
OS: Pop!_OS 20.04 LTS [linux version 5.4.0-7629-generic]

Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2

Environment:
  QT4_IM_MODULE="ibus"
  QT_ACCESSIBILITY="1"
  QT_IM_MODULE="ibus"

Features: QT_NO_EXCEPTIONS

Library info:
  PrefixPath: /usr
  DocumentationPath: /usr/share/qt5/doc
  HeadersPath: /usr/include/x86_64-linux-gnu/qt5
  LibrariesPath: /usr/lib/x86_64-linux-gnu
  LibraryExecutablesPath: /usr/lib/x86_64-linux-gnu/qt5/libexec
  BinariesPath: /usr/lib/qt5/bin
  PluginsPath: /usr/lib/x86_64-linux-gnu/qt5/plugins
  ImportsPath: /usr/lib/x86_64-linux-gnu/qt5/imports
  Qml2ImportsPath: /usr/lib/x86_64-linux-gnu/qt5/qml
  ArchDataPath: /usr/lib/x86_64-linux-gnu/qt5
  DataPath: /usr/share/qt5
  TranslationsPath: /usr/share/qt5/translations
  ExamplesPath: /usr/lib/x86_64-linux-gnu/qt5/examples
  TestsPath: /usr/tests
  SettingsPath: /etc/xdg

Standard paths [*...* denote writable entry]:
  DesktopLocation: "Desktop" */home/clinton/Desktop*
  DocumentsLocation: "Documents" */home/clinton/Documents*
  FontsLocation: "Fonts" */home/clinton/.local/share/fonts* /home/clinton/.fonts
  ApplicationsLocation: "Applications" */home/clinton/.local/share/applications* /usr/share/pop/applications /home/clinton/.local/share/flatpak/exports/share/applications /var/lib/flatpak/exports/share/applications /usr/local/share/applications /usr/share/applications
  MusicLocation: "Music" */home/clinton/Music*
  MoviesLocation: "Movies" */home/clinton/Videos*
  PicturesLocation: "Pictures" */home/clinton/Pictures*
  TempLocation: "Temporary Directory" */tmp*
  HomeLocation: "Home" */home/clinton*
  AppLocalDataLocation: "Application Data" */home/clinton/.local/share/QtProject/qtdiag* /usr/share/pop/QtProject/qtdiag /home/clinton/.local/share/flatpak/exports/share/QtProject/qtdiag /var/lib/flatpak/exports/share/QtProject/qtdiag /usr/local/share/QtProject/qtdiag /usr/share/QtProject/qtdiag
  CacheLocation: "Cache" */home/clinton/.cache/QtProject/qtdiag*
  GenericDataLocation: "Shared Data" */home/clinton/.local/share* /usr/share/pop /home/clinton/.local/share/flatpak/exports/share /var/lib/flatpak/exports/share /usr/local/share /usr/share
  RuntimeLocation: "Runtime" */run/user/1000*
  ConfigLocation: "Configuration" */home/clinton/.config* /etc/xdg/xdg-pop /etc/xdg
  DownloadLocation: "Download" */home/clinton/Downloads*
  GenericCacheLocation: "Shared Cache" */home/clinton/.cache*
  GenericConfigLocation: "Shared Configuration" */home/clinton/.config* /etc/xdg/xdg-pop /etc/xdg
  AppDataLocation: "Application Data" */home/clinton/.local/share/QtProject/qtdiag* /usr/share/pop/QtProject/qtdiag /home/clinton/.local/share/flatpak/exports/share/QtProject/qtdiag /var/lib/flatpak/exports/share/QtProject/qtdiag /usr/local/share/QtProject/qtdiag /usr/share/QtProject/qtdiag
  AppConfigLocation: "Application Configuration" */home/clinton/.config/QtProject/qtdiag* /etc/xdg/xdg-pop/QtProject/qtdiag /etc/xdg/QtProject/qtdiag

File selectors (increasing order of precedence):
  en_US unix linux pop

Network:
  Using "OpenSSL 1.1.1f  31 Mar 2020", version: 0x1010106f

Platform capabilities: ThreadedPixmaps OpenGL ThreadedOpenGL WindowMasks MultipleWindows ForeignWindows NonFullScreenWindows NativeWidgets WindowManagement SyncState RasterGLSurface SwitchableWidgetComposition

Style hints:
  mouseDoubleClickInterval: 400
  mousePressAndHoldInterval: 800
  startDragDistance: 19
  startDragTime: 500
  startDragVelocity: 0
  keyboardInputInterval: 400
  keyboardAutoRepeatRate: 30
  cursorFlashTime: 1000
  showIsFullScreen: 0
  showIsMaximized: 0
  passwordMaskDelay: 0
  passwordMaskCharacter: U+2022
  fontSmoothingGamma: 1.7
  useRtlExtensions: 0
  setFocusOnTouchRelease: 0
  tabFocusBehavior: Qt::TabFocusAllControls 
  singleClickActivation: 0

Additional style hints (QPlatformIntegration):
  ReplayMousePressOutsidePopup: 0

Theme:
  Platforms requested : pop,gtk3,gnome,generic
            available : 
  Styles requested    : fusion,windows
         available    : Windows,Fusion
  Icon theme          : Adwaita, gnome from /usr/share/icons
  System font         : "Sans Serif" 9

Fonts:
  General font : "Sans Serif" 9
  Fixed font   : "monospace" 9
  Title font   : "DejaVu Sans" 12
  Smallest font: "DejaVu Sans" 12

Palette:
  QPalette::WindowText: #ff000000
  QPalette::Button: #ffefefef
  QPalette::Light: #ffffffff
  QPalette::Midlight: #ffcbcbcb
  QPalette::Dark: #ff9f9f9f
  QPalette::Mid: #ffb8b8b8
  QPalette::Text: #ff000000
  QPalette::BrightText: #ffffffff
  QPalette::ButtonText: #ff000000
  QPalette::Base: #ffffffff
  QPalette::Window: #ffefefef
  QPalette::Shadow: #ff767676
  QPalette::Highlight: #ff308cc6
  QPalette::HighlightedText: #ffffffff
  QPalette::Link: #ff0000ff
  QPalette::LinkVisited: #ffff00ff
  QPalette::AlternateBase: #fff7f7f7
  QPalette::NoRole: #ff000000
  QPalette::ToolTipBase: #ffffffdc
  QPalette::ToolTipText: #ff000000
  QPalette::PlaceholderText: #80000000

Screens: 2, High DPI scaling: inactive
# 0 "eDP-1-1" Depth: 24 Primary: yes
  Manufacturer: SDC
  Model: 
  Serial number: 
  Geometry: 3840x2160+0+4320 Available: 3840x2160+0+4320
  Virtual geometry: 7680x6480+0+0 Available: 7680x6480+0+0
  2 virtual siblings
  Physical size: 344x194 mm  Refresh: 60 Hz Power state: 0
  Physical DPI: 283.535,282.804 Logical DPI: 192,192 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 2
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

# 1 "HDMI-0" Depth: 24 Primary: no
  Manufacturer: Dell Inc.
  Model: DELL P2715Q-
  Serial number: X24K162H158L-
  Geometry: 7680x4320+0+0 Available: 7680x4320+0+0
  Virtual geometry: 7680x6480+0+0 Available: 7680x6480+0+0
  2 virtual siblings
  Physical size: 597x336 mm  Refresh: 30 Hz Power state: 0
  Physical DPI: 326.754,326.571 Logical DPI: 192,192 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 2
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

LibGL Vendor: NVIDIA Corporation
Renderer: GeForce RTX 2070/PCIe/SSE2
Version: 4.6.0 NVIDIA 440.82
Shading language: 4.60 NVIDIA
Format: Version: 4.6 Profile: 2 Swap behavior: 0 Buffer size (RGB): 8,8,8 Depth buffer: 24
Profile: None (QOpenGLFunctions_4_6)


Vulkan instance available
Supported instance extensions:
  VK_KHR_device_group_creation, version 1
  VK_KHR_display, version 21
  VK_KHR_external_fence_capabilities, version 1
  VK_KHR_external_memory_capabilities, version 1
  VK_KHR_external_semaphore_capabilities, version 1
  VK_KHR_get_display_properties2, version 1
  VK_KHR_get_physical_device_properties2, version 1
  VK_KHR_get_surface_capabilities2, version 1
  VK_KHR_surface, version 25
  VK_KHR_surface_protected_capabilities, version 1
  VK_KHR_xcb_surface, version 6
  VK_KHR_xlib_surface, version 6
  VK_EXT_acquire_xlib_display, version 1
  VK_EXT_debug_report, version 9
  VK_EXT_debug_utils, version 1
  VK_EXT_direct_mode_display, version 1
  VK_EXT_display_surface_counter, version 1
  VK_KHR_wayland_surface, version 6
Supported layers:
  VK_LAYER_MESA_overlay, version 1, spec version 1.1.73, Mesa Overlay layer
  VK_LAYER_LUNARG_standard_validation, version 1, spec version 1.0.131, LunarG Standard Validation Layer
Available physical devices:
  API version 1.2.131, vendor 0x8086, device 0x3E9B, Intel(R) UHD Graphics 630 (CFL GT2), type 1, driver version 20.0.4  API version 1.1.119, vendor 0x10DE, device 0x1F10, GeForce RTX 2070, type 2, driver version 440.328.0

**Comment by dg0yt** [comment] 2020-05-21 17:19
> Theme:
Platforms requested : pop,gtk3,gnome,generic
available :
Styles requested : fusion,windows
available : Windows,Fusion
Icon theme : Adwaita, gnome from /usr/share/icons

No Platforms "available"? I get at least kde,gtk2,gtk3.
This is chosen by setting QT_QPA_PLATFORM=..., e.g. in Terminal:
~~~
QT_QPA_PLATFORMTHEME=gtk2 Mapper
~~~

In addition, there usually also various platform plugins which can be chosen by a command line parameter in Qt apps, e.g.
~~~
Mapper --platform xcb
~~~

You may also try running with software OpenGL instead NVIDIA:
~~~
LIBGL_ALWAYS_SOFTWARE=1 Mapper
~~~

**Comment by cmorse01** [comment] 2020-05-22 12:26
I tried those system variables to no avail.

Am attempting to compile from source, though admittedly its been a few years and I never did a lot of C programming.  A couple errors get thrown in CMAKE:  (I apologize if these should be obvious to me)

-- The following OPTIONAL packages have not been found:
 * ClangTidy (required version >= 8)
 * IWYU (required version >= 0.12)

AND

-- Licensing information provided by: pop
CMake Error at doc/licensing/CMakeLists.txt:157 (include):
  include could not find load file:
    pop-licensing.cmake

followed by a series of licensing errors.

The first appears to just be required for developer convenience tools, and the second seems like it may be fine to ignore as well.

Also - should I uninstall my existing OOM via APT before attempting to compile from source?

Thanks..

**Comment by cmorse01** [comment] 2020-05-22 13:09
Also - this may be an unrelated thing, but I just noticed if I do an "apt list --installed" command, I get
openorienteering-mapper/unknown,now 0.9.3-0+29.1 amd64 [installed]

every other package listed shows the version to be focal, whereas mapper shows as unknown?

**Comment by dg0yt** [comment] 2020-05-22 20:20
Just to verify: you are really using the 20.04 package? You not just remained on the 19.10 repository?

`dpkg-query -s openorienteering-mapper` will list the dependencies, which will differ for 19.10 vs. 20.04.

> Also - this may be an unrelated thing, but I just noticed if I do an "apt list --installed" command, I get
> openorienteering-mapper/unknown,now 0.9.3-0+29.1 amd64 [installed]
> 
> every other package listed shows the version to be focal, whereas mapper shows as unknown?

This is okay AFAICT: the package just doesn't come from Ubuntu focal.

**Comment by dg0yt** [comment] 2020-05-22 20:29
> -- Licensing information provided by: pop
> CMake Error at doc/licensing/CMakeLists.txt:157 (include):
> include could not find load file:
> pop-licensing.cmake

Pass `-DLICENSING_PROVIDER=ubuntu` or  `-DLICENSING_PROVIDER=OFF` to `cmake`.

> Also - should I uninstall my existing OOM via APT before attempting to compile from source?

It depends. I just build and run, but never install from my development tree. However, I think the default configuration will install everything to the `/usr/local` prefix, so it doesn't interfer. But nobody cleans up in `/usr/local`... sometimes I do install tests with `-DCMAKE_INSTALL_PREFIX=/tmp/foo` or at least I run install with `DESTDIR=/tmp/foo`

(I thought of rebuilding the binary package from the Ubuntu 20.04 source package, but this will fail with above licensing error unless modified.)

**Comment by cmorse01** [comment] 2020-05-22 22:46
Yes, I'm on the 20.04 respository.
deb http://download.opensuse.org/repositories/home:/dg0yt/Ubuntu_20.04/

May try compiling from source later on...

**Comment by cmorse01** [comment] 2020-05-25 21:44
Still no resolution - other than to avoid cuttings lines on my main (Linux) system.  
But I did find a second tool that causes the instant logout to occur - the Scale Objects tool has the same effect - just in case there is any common code between them that might suggest a culprit.  I have never tried using this particular tool, but was trying to shrink the OOM logo to squeeze onto the map a little neater...

**Comment by dg0yt** [comment] 2020-05-26 04:29
Do you now run the binary which you compiled youself?
So far, the only common thing is Pop!OS...

**Comment by cmorse01** [comment] 2020-05-26 19:19
I have not attempted to compile my own binary yet.  Working on a project at the moment, so unwilling to take the risk of compilation going haywire and having to restore my system from a backup.  I realize its fairly unlikely, but I haven't compiled code in a while so its not exactly second nature at the moment.  

Getting creative to avoid needing to use the cut object tool for now.  (Drafting short segments, deleting endpoints or just deleting lines and redrawing).  Once I've finished up the current small project I'll give re-compilation a shot.

**Comment by lpechacek** [comment] 2020-05-27 15:11
A dump of my thoughts on this issue with a (serious) recommendation at the end.

I've installed Pop! into a VirtualBox VM. I chose the Intel/AMD variant and expected Mapper to run fine in this environment. Well, it did. No crashes. Next, I thought about what makes the Cut tool so special that it makes Mapper die right after the tool selection. The cursor image seems to be a good candidate. Then I thought which other tool has a similarly large cursor shape and spotted the Scale objects tool. One of the previous comments confirms my observation that the cursor size matters.

The test with the Intel driver suggests that there might be something wrong with the cursor rendering in general. It's hard to say at this point if the observed symptoms belong to an installation issue or a plain software bug, however.

At this point, I recommend taking this issue up with System76 so that they can examine the defect further.

**Comment by cmorse01** [comment] 2020-05-27 17:26
Thank you.  Your thoughts about cursor size may be spot on.  I'm on a 4k laptop and always run in HiDPI mode.  Since the cursor appears about 4x expected size when I select the tool (the actual GNOME crash occurs when I move the mouse) it occurred to me that cursor scaling may be at play.  I dropped the system to LoDPI mode and the tools work as expected.  I have submitted a service request to System 76.  In the meantime I know I can do most work in HiDPI (preferred) and just drop to LoDPI for curve cutting operations.  Thanks again for sharing your thoughts..

**Comment by lpechacek** [comment] 2020-05-27 19:53
Your remark about HiDPI (daemon) made me take a closer look at this component. The daemon is not part of any of the distros I'm using, and Google search results suggest that it is [an enhancement specific to Pop!_OS](https://blog.system76.com/post/174414833678/all-about-the-hidpi-daemon). One more reason to tell System76 about the bug.

As a side note, Qt has its own [means for handling hi-DPI displays](https://doc.qt.io/qt-5/highdpi.html). So switching to LoDPI mode and running Mapper like `QT_SCALE_FACTOR=2 Mapper` from the command line might be an alternative. Feel free to adjust the scale factor to your needs.

**Comment by lpechacek** [comment] 2020-05-29 07:30
At this point I believe it is safe to close this issue. If the crash turns out to be a Mapper issue after all, feel free to reopen. Thanks!

**Closed by lpechacek** 2020-05-29 07:30 UTC
