### ISSUE TITLE
Fill bounded area "leaks" into internal objects

### ISSUE THREAD

**Issue by jan-gerard** [OpenOrienteering/mapper#628] opened 2016-03-22 09:18 UTC
If I have two concentric line objects, and I fill the ring between them (example; may be any other combination of shapes), the innermost area gets filled as well, although I would expect only the area between them to be filled, when both are closed objects.

**Comment by Symbian9** [comment] 2016-03-22 11:19
Please, read the manual about "Cut away from area", "Area XOr"
http://www.openorienteering.org/mapper-manual/pages/toolbars.html#drawing

**Comment by jan-gerard** [comment] 2016-03-22 14:43
I know how to use "cut away" and related tools. I think that the fill tool should fill the white space, not everything else contained by this white space. I could fill an area, and then select every inner element and cut that out from the just-filled area, but selecting all the elements withing the fill, which might be covered by the fill, may be quite some work. 
For example, I have blocks of houses, private properties, and sidewalks. I want the fill in the remaining paved area. Or I have the houses and the sidewalks, and want to fill in the rest as private impassable area.
See for example [http://pasteall.org/pic/100852](http://pasteall.org/pic/100852) which becomes [http://www.pasteall.org/pic/100853](http://www.pasteall.org/pic/100853)

**Comment by dg0yt** [comment] 2016-03-22 20:08
Duplicate of #496.

**Closed by dg0yt** 2016-03-22 20:08 UTC
