### ISSUE TITLE
Enhancement Request - customize shortcut keys

### ISSUE THREAD

**Issue by 3o1415** [OpenOrienteering/mapper#1269] opened 2019-06-21 14:25 UTC
I've found most of the existing shortcut keys to be extremely useful for efficient workflow. However, some are awkwardly positioned on the keyboard.

### Current behavior
Currently shortcuts are hard-coded in. (At least AFAIK). 

### Desired behavior
Possibility to customize key-mapping to individual tools/functions, including Ctrl-, Alt- and Shift-combinations. For example, Edit_Lines (L) and Edit_Object(E) tools are awkwardly far apart on the keyboard to fluidly switch back and forth.

### Configuration
Mapper Version: 0.8.4
Operating System: Win7

**Comment by dg0yt** [comment] 2019-06-21 19:37
Duplicate of #101.

**Closed by dg0yt** 2019-06-21 19:37 UTC
