### ISSUE TITLE
Involuntarily adding stuff on map

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#982] opened 2017-10-05 08:55 UTC
### Steps to reproduce
It is very easy involuntarily add stuff on map (Android app). You can touch screen by accident or forget that you are in drawing or scriblling mode. And voilà there are objects on map you are not aware of. It is hard to spot these mistakes. (In "manual" you could always go back to mylar and see the original. You can not do that in the app.)

### Expected behaviour
So there is a strong need to avoid mistakes being made. I believe there are more ways how to do it. My suggestion would be:
After some time of no action (10 secs?) automatically switch buttons to Pan map button. This way you omit chances of accidentally adding stuff on map (the time might be optional).

### Configuration
Android App 0.7.0

**Comment by Zerbembasqwibo** [comment] 2017-10-08 20:55
I have exactly same thoughts. But, maybe better, or another way, to have some kind of check compared to you GPS-position (if used). That means you will be given some kind of warning if you try to draw an object more than X meter from your position.

The "switch to pan-mode" idea is anyway maybe easier and best way? I think 10 sec might be good, but also maybe after drawing point object time could be much shorter or zero? If you accidentally draw line/area object you will probalby see it?

**Comment by AskoMaatta** [comment] 2022-09-24 06:37
When you select a symbol in OOMapper (Touch Mode User Interface), it has a move function by default on. It's a bit tricky, because you can accidentally use a pen to move, for example, the contour or some area symbols.
It would be great if the move and delete functions could be protected and they could be released in some clever way

Asko M

**Comment by Zerbembasqwibo** [comment] 2022-09-24 07:09
Also, would be nice to have a warning, if you try to edit something more
far away than X meter (50 default, set by user) from your GPS position.

Purpose; to prevent editing by mistake at field work.


lördag 24 september 2022 skrev AskoMaatta ***@***.***>:
> When you select a symbol in OOMapper (Touch Mode User Interface), it has
a move function by default on. It's a bit tricky, because you can
accidentally use a pen to move, for example, the contour or some area
symbols.
> It would be great if the move and delete functions could be protected and
they could be released in some clever way
>
> Asko M
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.<
https://ci5.googleusercontent.com/proxy/gEqvjmCvv5PbUGHCDlCNQIZYMWkKss3nRGusN7aMWREuKxC-yj_aFjIOE5aBR_0ImKGHcWa6UEM8rmO4U6mavzXcBhfozgsvMvvkHHfUUOrae1uS3N-QZXrWP2OLX6H4fpQOKCMnBvGrgLYi__rmU-D3paAQXtuwu7Y3D3FrIY3BlpU66yGCVG3iRaJ6L0ylHkv-1ki2Ps3ImrrMI7PHoFuNq1vxcZlg-PYeVhTi4w=s0-d-e1-ft#https://github.com/notifications/beacon/AD3LQD44QJ4LDU27MTVCIKLV72OURA5CNFSM4D53ALPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOJLVHVCY.gif>Message
ID: ***@***.***>

**Comment by lpechacek** [comment] 2022-09-24 07:53
Thanks, Asko, for your comment. I'll shamelessly use this opportunity for a self-promo as I think that we have made a few steps to prevent the unintentional move of objects.

> When you select a symbol in OOMapper (Touch Mode User Interface), it has a move function by default on. It's a bit tricky, because you can accidentally use a pen to move, for example, the contour or some area symbols.

I'm not sure about this statement. When I select the pan mode in OO Mapper touch UI, then choose a symbol, the user interface switches to drawing mode. That is, the editing mode (the arrow/triangle icon at the top) is inactive.

Would you mind elaborating on the problematic use case, please?

> It would be great if the move and delete functions could be protected and they could be released in some clever way.

Mapper has the undo function. I acknowledge, however, that the problem is to spot the unintentional move in the first place. I myself do not hit this problem in my fieldwork, so I'd welcome a better description of the situation.

Now to the self-promo. I think that the original problem described by @ollesmaps (touching the screen when not working with the map) has been solved to a large degree with #1872 (Stylus only input) on devices that do have the independent input channel like Samsung S-Pen. For tablets that have only the capacitive touch screen, a Bluetooth mouse or trackball might be the solution.

We have also enlarged the move object frame in #1587 (EditPointTool,EditLineTool: Enlarge object frame (GH-980)). That helps avoiding unexpected actions as well. For the move of large objects, we do have  #1244 (Enhancement: Warn upon unintentional move of objects). So the request is in place but someone will have to contribute the code. :)

There is also code change https://github.com/lpechacek/mapper/commit/ad249d2d9ce7b932c961e3637b8ced043fa66f4b that makes Mapper select the pan tool on start up but I never proposed the merge as I have integrated a manual switch to the pan mode into my daily routine. Anyway, given that @Zerbembasqwibo has shown interest in the function, I'll consider placing a merge request.

**Comment by pkturner** [comment] 2022-09-25 03:12
> We have also enlarged the move object frame in #1587 (EditPointTool,EditLineTool: Enlarge object frame ([GH-980](https://github.com/OpenOrienteering/mapper/issues/980))). That helps avoiding unexpected actions as well.

That helps in some cases. 

The move object frame is a big target, and occasionally it happens to me that I'm intending to tap on another object that's close to the frame. But when I tap, the stylus touches near the frame and slips a bit, moving the originally selected object slightly. The change is so slight it might not be noticed, and usually my reaction is to tap on the other object again. Then I realize that I've been tapping the move object frame, and I _may_ have changed the framed object unintentionally.

To deal with a possibly-moved object, I must use undo, and try to see whether the undone action is unintentional. As a result, having 'undo' is not a clean solution because the user doesn't readily know whether using it will fix the situation.

I could prevent this if there were a 'select none' button in the touch UI. For lack of 'select none', I find myself cleaning up the portion of the screen that's of interest to me by selecting a little boulder located at the far corner of the screen.

**Comment by krticka** [comment] 2022-09-25 08:56
I would be happy to have button or menu option to deactivate object frame completely. When mapping I would be OK just with vertex points when clicking on object.

**Comment by lpechacek** [comment] 2022-09-25 12:42
@pkturner I hit the same problem occasionally. Selecting the right object may require multiple "clicks" (touches with the stylus). It looks to me like Luděk's proposal might be a solution. I myself stumble over the object move function more often than I use it.

**Comment by mlerjen** [comment] 2022-09-26 06:57
Moving and deleting features can be intentional steps e.g.  while revising a map. I would thus not make these to cumbersome for the intended use (e.g. popping up dialogs).

My favorite solution would be to have sounds for moving and deleting evtually. also for adding features. It would be an easy way to check the congruence between the mappers intention and the effective action on the app.

(and btw. yes: stylus only input is a great feature)

**Comment by ollesmaps** [comment] 2022-11-04 08:14
I must confirm I do not have troubles with unintentional movement of objects anymore. Thanks!

The only thing I notice is that:

- I sometimes delete an object by mistake when switching from panning to editing.
- That is because the Edit button and Delete button are next to each other. Quick undu solves this. 
- Anyway I give reference to the GUI Button clashes issue #952 
- and also  #958 (as mentioned by @mlerjen "_My favorite solution would be to have sounds for moving and deleting eventually. also for adding features. It would be an easy way to check the congruence between the mappers intention and the effective action on the app_.")

I suggest to close this issue.

**Closed** 2022-11-04 08:14 UTC
