### ISSUE TITLE
Drawing path straight segments - abrupt end

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#1180] opened 2018-11-15 14:17 UTC
### Steps to reproduce
1. In the Draw paths mode when drawing straight segments, sometimes path ends unintentionally (I would say every 15th segment ends like this).
2. Usually after drawing short segments.
3. Usually when drawing in a fast pace.

This concerns Android only, no problem on PC.
I assume the abrupt end of path drawing is caused by confusion with doubleclick.

### Configuration
Mapper Version: 0.8.1
Operating System: Android 7.1.1, Samsung S Pen

**Comment by lpechacek** [comment] 2018-11-19 10:16
Successfully replicated the bug.

**Comment by lpechacek** [comment] 2018-11-22 12:00
Looks like the above fix works but I'd like to make a more thorough root cause analysis before placing a pull request.

**Comment by ollesmaps** [comment] 2020-06-23 09:45
I have not experienced the faulty behaviour any more. Is the code incorporated?

**Comment by lpechacek** [comment] 2020-06-23 12:19
Nope, the code change never made it into Mapper. However, I suspect the bug disappeared due to a Qt upgrade. After all, it is Qt which collects the input events and interprets them for the application.

At this point, I suggest closing the ticket and reopening it in case the issue resurfaces. Thanks!

**Closed** 2020-06-23 12:35 UTC
Labels: mobile version

**Comment by lpechacek** [comment] 2026-01-04 19:04
@dg0yt, understood. I've replaced the left mouse button microswitch in my mouse assuming that it was faulty and generated noise. The behavior is the same with the new button switch.

IMHO, line drawing should not be ended with double click as the predefined doubleclick rate limits "power" users in the speed of drawing. The drawing software should react only to right mouse button. Anyway, let's close this issue again, as this seems to be a very rare issue in o-map making. Thanks!
