### ISSUE TITLE
OCAD virtual gap import

### ISSUE THREAD

**Issue by valdisj** [OpenOrienteering/mapper#2002] opened 2021-11-08 20:30 UTC
OCAD has a function, where one can draw a line, and then use "CTRL + cut" to do a virtual gap on the line. Some mappers use this extensively to "virtually cut" contours where pits, or when magnetic north lines are cut in some places, or in other situations on any line object. Mappers say, that this reduces problem of too many short lines and makes the workflow easier for cutting.

### Steps to reproduce
1. open any OCAD file, which has "virtual gap" used on any of the lines (contours or other)

### Actual behaviour
OOM ignores virtual gap.
<img width="226" alt="image" src="https://user-images.githubusercontent.com/5184678/140813468-9c54a628-75a5-4dfe-a15d-2b48f69f4827.png">

### Expected behaviour
OOM imports and represents virtual gap correctly.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/5184678/140813510-1abd5bc6-1da7-4af3-a1fb-2f086a5870df.png">

### Configuration
Mapper Version: OOM 0.9.4 and OOM 0.9.5
Operating System: Macos

**Comment by dg0yt** [comment] 2021-11-09 04:44
Thanks for reporting. It is a duplicate of #150.

**Closed by dg0yt** 2021-11-09 04:44 UTC
