### ISSUE TITLE
ISMTBOM2022 Symbol set

### ISSUE THREAD

**Issue by eolmapper** [OpenOrienteering/mapper#2033] opened 2022-01-31 14:13 UTC
Create ISMTBOM2022 Symbol set.
[PDF ISMTBOM2022](https://onedrive.live.com/?authkey=%21AE8iquTM1ZY3UDM&cid=663580750D0C0BCE&id=663580750D0C0BCE%2147463&parId=663580750D0C0BCE%2118039&o=OneUp)

**Comment by Symbian9** [comment] 2022-02-02 09:22
Duplicate of https://github.com/OpenOrienteering/mapper/issues/1107

**Closed** 2022-02-02 09:28 UTC
