### ISSUE TITLE
ISOM 2017 symbol sets (ex-ISOM 201X project)

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#612] opened 2016-03-03 11:29 UTC
Discussions (please, read them all):
1.1) http://www.attackpoint.org/discussionthread.jsp/message_1099951
1.2) http://ocad.com/blog/2015/12/the-new-orienteering-map-specification-isom-201x/
1.3) https://m.facebook.com/permalink.php?story_fbid=1233833533299441&id=177518995597572
1.4) https://m.facebook.com/permalink.php?story_fbid=1251215201561274&id=177518995597572

And here are some PDF's
2.1) http://lazarus.elte.hu/mc/14icom/08-isom201x.pdf
2.2) www.orientering.se/ImageVaultFiles/id_82109/cf_78/20141115_ISOM.PDF
2.3) http://orienteering.asn.au/wp-content/uploads/2015/10/20160112-Orienteering-Australia-comments-on-ISOM-201x.pdf
2.4) http://orienteering.asn.au/wp-content/uploads/2015/10/ISOM-20151120-comments-to-ISOM-201x-Final-draft-A-O-Uppill.pdf
2.5) http://www.orientering.se/ImageVaultFiles/id_42104/cf_78/ISOMrevisionFirstDraft201305.PDF
2.6) http://www.orientering.se/ImageVaultFiles/id_111233/cf_78/201512_isom201x_part1_general_content.PDF

**Comment by dg0yt** [comment] 2016-03-22 20:38
There is 201x symbol set at http://orientering.no/nyheter/har-du-innspill-til-den-nye-kartnormen/.

**Comment by Symbian9** [comment] 2016-04-06 03:40
@dg0yt, presented .omap on site from your link need correction.
Firstly what I see is that text has outlines, but in specification there no outlined text symbols.
Also need check all dimensions in every symbols.
But, anyway its a good start point for creating this symbol set for next OOMapper release.

**Comment by dg0yt** [comment] 2016-04-06 04:39
First of all IOF has to approve the next version of ISOM.

**Comment by Symbian9** [comment] 2016-04-06 11:49
@dg0yt, yeah, but is Mapper ready for upcoming ISOM 201x standart?(I thin IOF approve it this year anyway)

**Comment by yevhenmazur** [comment] 2017-01-16 17:30
I've prepared ISOM 201x implementation for my own use. It is based on file provided by orientering.no, but it has few important updates:
- Correct symbol names
- Full symbols description, according to ISOM 201X Final Draft from Dec 2015
- Corrections in text symbols
- More variants for symbols 402 (Open land with scattered trees) and 404 (Rough open land with scattered trees)
- OOMapper-specific symbols like North Line Pattern, Logo and Simple Orienteering Course.

[isom-201x-finaldraft-11-2015-unofficial_symbols.omap.zip](https://github.com/OpenOrienteering/mapper/files/709037/isom-201x-finaldraft-11-2015-unofficial_symbols.omap.zip)
This symbol set already been tested on our local events. IMO it is ready to production.

**Comment by Symbian9** [comment] 2017-01-16 21:20
> IMO it is ready to production.

ISOM 201X still not approved by ISOM MC and not recommended for use
* http://lazarus.elte.hu/mc/17icom/07.pdf

**Comment by mlerjen** [comment] 2017-01-19 13:13
It is expected that the Council will approve the ISOM2018 at its meeting this summer.

Since the version published by the Norwegian federation, there where a lot of changes. It does not seem meaningful to me to produce unofficial pre-versions. As far as I can see from here now, there will only be small stuff Mapper can not handle. 

Some point though: symbols (Boulderfield, Stony ground, Brokenground) will likely be switched to area symbols (with standardized densities). This opens questions on 
-> "edge handling" (if the filling pattern reaches over an edge it can either be cut, omitted or drawn in its entirety ). 
-> stochastic spreading pattern (generation of a fill pattern with a variation of rotation angle and distance between the fill symbols.

Here below a screenshot from OCAD12 with the areas outline highlighted. There you can see the same symbol with the three different edge options. 
![image](https://cloud.githubusercontent.com/assets/15611653/22107720/b7b66eda-de4f-11e6-98d3-7c8e065b6398.png)

**Comment by mlerjen** [comment] 2017-01-23 13:01
Update. It went faster than wee thought. The ISOM 2017 will be published soon (in about 4-8 weeks).

**Comment by Symbian9** [comment] 2017-02-10 08:01
IOF Council Meeting minutes regarding ISOM2017 on 01.21.2017 (paragraph 16.1) 
* http://orienteering.org/wp-content/uploads/2013/02/Minutes-of-Council-meeting183.pdf

ISOM 2017 Council preliminarily approved the International Specification for Orienteering Maps ISOM 2017 for final editing. The approval was given based upon the final edit being in accordance with the consultation which had been conducted prior to the Council meeting, regarding the 2 items:
* That the concept of impassable features being forbidden to cross be removed from the relevant symbols in the specification and dealt with instead in the IOF rules.
* That texts regarding map scale, which do not affect the technical specification and generalisation requirements, be removed from the specification and instead dealt with in the IOF rules. Final editing would be conducted by the MC in collaboration with LZ (Laszlo Zentai), MS (Mikko Salonen) and MD (Michael Dowling) and final Council approval of the specification would be given by e-mail decision as soon as possible.

**Comment by dg0yt** [comment] 2017-02-11 12:41
Still no access to the *current* draft.

**Comment by Zerbembasqwibo** [comment] 2017-02-27 19:35
According to discussion on orienterare.nu the norm now is finally revised and corrected, only some small pictures left to produce. So the ISOM201X can soon be called ISOM2017.

http://orienterare.nu/t/1816#answer-231170

**Comment by dg0yt** [comment] 2017-04-04 15:47
The [International Specification for Orienteering Maps (ISOM) 2017](http://orienteering.org/wp-content/uploads/2010/12/ISOM-2017.pdf) has been published. According to the [announcement on the IOF webpage](http://orienteering.org/international-specification-for-orienteering-maps-isom-2017-has-been-published/), its use in IOF events is optional in 2017 but becomes standard in 2018.

**Comment by Zerbembasqwibo** [comment] 2017-04-04 15:51
Here we go! 0,15 mm between everything will turn the world upsidedown.

2017-04-04 17:47 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by Symbian9** [comment] 2017-04-04 17:44
@dg0yt, So, did OOMapper 0.6.x still support all futures needed for symbols from ISOM 2017?  Or its need some new futures, that could be implemented only in next 0.7.x?

P.S.: Hope that OOMapper 0.6.9 with ISOM 2017 (without GDAL dependency) will be created when we make new symbol sets.

**Comment by dg0yt** [comment] 2017-04-05 06:22
@Symbian9 It is called features, not futures. And if there ever will be a 0.6.9, it will only fix serious bugs, not add new features.

**Comment by dominikzalewski** [comment] 2017-04-05 07:17
Think it's live since yesterday:

http://orienteering.org/wp-content/uploads/2010/12/ISOM-2017.pdf

From what I noticed, there is an interesting variation of symbols 402 and 404. Also old symbol 411 (forest runnable in one direct) disappeared in favor of 406, 408 and 410.

Think the priority of this one should be bumped :)

**Comment by dg0yt** [comment] 2017-04-05 07:24
Well, there is the preliminary symbol set from @yevhenmazur, in the comment from Jan 16. Review and comment.

Unfortunately, ISOM 2017 changes a lot of symbol numbers. This is how NOT to evolve standards, because it introduces disambiguities. No easy migration path for existing maps...

**Comment by dominikzalewski** [comment] 2017-04-05 07:38
Looks like the symbol set you are referring to needs to be updated quite a lot. Prominent features have changed in a different direction than expected. The triangles and asterisks are not for all types (landform, water, man-made). Also, the directional runnability is not reflected :)

Other than that I'm happy to see that as always, OO Mapper is the cutting edge technology! Wondering how long it will take for OCAD to catch-up!

**Comment by Zerbembasqwibo** [comment] 2017-04-05 07:45
Is there a need for a tool to convert old ISOM2000-maps to ISOM2017?

A "plugin"?


2017-04-05 9:38 GMT+02:00 dominikzalewski <notifications@github.com>:

**Comment by Zerbembasqwibo** [comment] 2017-04-05 07:57
I just started to look at it.

ISOM2000  ISOM2017
101 101 Contour
102 102 Index contour
103 103 Form line
104 - Slope line
105 Contour value
….
There is a very urgent need that IOF presents valid symbol gallerys for
OCAD/OOM and other used tools.

Since there is no number for "Index contour value", not even a well defined
name, means every map drawer must find out what to call it. 102.1 or what?
But it's same in ISOM 2000.

Slope line is another one. Now you must have different slope lines for
contour (0.14 mm) and form line (0.10 mm). What numbers to use?

Slope line contour: 101.1?
Slope line form line 103.1?

And maybe you also must use slope line Index contour 102.1?

In the introduction there is written "Since then some technological
developments have occurred as well as some changes in the event programme.
These developments have been taken into consideration when revising the
ISOM" but now it seems the technical questions of how to implement this in
digital tools seems to have been forgotten?

Maybe there is no big deal, but why not make it complete during these seven
years the update process have been going on?

2017-04-05 9:45 GMT+02:00 Sven Lundbäck <sven.lundback@gmail.com>:

**Comment by Symbian9** [comment] 2017-04-21 16:19
Changes from ISOM 2000 to ISOM 2017. This document is addition to new orienteering map specification.
* http://orienteering.org/wp-content/uploads/2017/04/Changes_from_ISOM2000_to_ISOM2017.pdf

**Comment by 999999333** [comment] 2017-04-21 17:06
Is there somebody working on new ISOM 17 symbolset? I can help.. 😃

**Comment by yevhenmazur** [comment] 2017-04-21 17:36
@999999333 Please help to test it. Here's the updated version (according to ISOM 2017 v1)
https://1drv.ms/u/s!AqM4dAso-t50gwbhkG9rtj82pYIn

**Comment by lpechacek** [comment] 2017-04-25 06:53
@yevhenmazur good job done! I have reviewed the symbol set with ISOM 2017 at hand and here are my observations:

1. minimum area is not set on area symbols
2. area patterns orientated to north are rotatable but they should not - 307.0, 308, 310, 407, 409, 412, 520.1, 709, 709.3
3. prominent water feature (313) asterisk is too small - it has 0.77mm diameter and should be 0.9mm
4. start triangle (701) is too big, should be 6mm tip to tip
5. control point symbol (703) - circle is too wide, should be 5mm center to center
6. finish (706) - inner circle is too wide, should be 4mm center to center

**Comment by dg0yt** [comment] 2017-04-25 07:49
@lpechacek yevhenmazur added a pull request, #860.

**Comment by lpechacek** [comment] 2017-05-02 11:02
As discussed in pull request #860, ISOM 2017 symbol set should be derived from the existing Mapper files. I looked into the matter over the weekend and a rough draft is at https://github.com/lpechacek/mapper/tree/isom2017/symbol%20sets/15000 . I'm aware of issue #861 and the file attached there. Will have a look at it ASAP but not before Thursday.

What has been done so far:
- defined new shapes for the special landform and water features
- defined new area symbols for landform, boulder, water and vegetation features
- dropped overprinting symbols
- defined new colors for the above symbols accordingly

To do
- finish man-made and technical symbols
- check/adjust symbol textual descriptions
- review all symbols for accordance with the standard
- check consistency of derived symbol numbering and symbol combinations (lake, shallow water, contour lines, ...)

Open question:
Is area between lines of 215 Trench symbol supposed to be opaque white or should it be transparent?

**Comment by Freemapper** [comment] 2017-05-05 07:07
I tried importing and changing the new symbol-set ISOM2017_15000.xmap but the whole background turned brown. Unchecked the crosses in theoption boxes but had the same result. 
Done this on a existing basemap. The white backround changed to brown only in the squarefield of 2,5*2,5 km where I had imported lidar data and done field wor,, but not in the other parts of my map done in the same way.
Waths my problem? How to solve it?  Im using latest version of *OOM.
Can I change the signs one by one manually? Like importing only the new form lines and changing them on my map?

**Comment by dg0yt** [comment] 2017-05-05 07:16
Freemapper, that's a separate issue.

There is no background color, so there is no easy answer.
- During import, symbols might have been replaced incorrectly. The default matching is by numbers, which is bound to fail for the ISOM 2000 to 2017 transition. (Thanks a lot, MC). But you can modify the matching.
- During import, colors might have been merged incorrectly. This is tricky, given a mix of old symbols and new symbols, and old colors and new colors.
- Something else.

Probably there won't be much help unless there are (minimal) test files which reproduce the issue. If you don't want to share the files in the public, there is always another way (e-mail, private upload). N

**Comment by Freemapper** [comment] 2017-05-05 14:51
Hi Kai! Thanks for the answer. I send you a file of the basemap Im working
on. Hope it´s not to big.

Best regards

Stefan from Sweden /Freemapper

2017-05-05 9:16 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by Freemapper** [comment] 2017-05-06 07:07
I have found the background turns brown and cannot be changed back to white again, after having imported template "contours.dfx" wich I have after processing Lidar-data in kartapullauttin. 
This file "contours.dfx" gives 30 cm contourlines as a background template but is a big file forcing me to upgrade my surfplate to a Huawei with 4 Gb RAM-memmory (about 350 euro). The curves are beautiful to have but the file "ISOM2017_15000.xmap" for upgrading the symbols, destroys the map (=Warning!)

I`m lucky to have tried on a backupp-file only so its just a day´s work wich is destroyed.
(Have tested this after imorting one more of this template "contours.dfx"-file in another part of the basemap)

**Comment by dg0yt** [comment] 2017-05-06 07:26
FreeMapper, even if this is related to ISOM2017_15000.xmap, please report this a separate issue.

**Comment by dominikzalewski** [comment] 2017-05-06 07:27
FYI, they've already updated the standard on the 1st of May. List of changes here: http://orienteering.org/wp-content/uploads/2017/04/Document-edits.pdf

**Comment by Freemapper** [comment] 2017-05-06 15:42
Hi Dominik! Thanks for updating me of the ISOM 2017 changes. I googled on
your name and found we share the same interests of rock climbing and
orienteering. Are you in to the alpine climbing or more to sportclimbing
bolted routes/Indors? I do it all.

Best regards
Stefan from Sweden

2017-05-06 9:27 GMT+02:00 dominikzalewski <notifications@github.com>:

**Comment by dg0yt** [comment] 2017-05-06 15:45
@Freemapper Your e-mail is recorded in our ISOM 2017 issue discussion, being relayed to min. 9 people. Please be careful when responding. I will clean this up later.

**Closed** 2017-06-27 06:58 UTC
Labels: ISOM2017, symbol sets

**Comment by Zerbembasqwibo** [comment] 2017-06-27 09:47
I tried 0.7.20170627. 207.1 looks strange in very much zoom. Definition looks OK woth three coordinates.

![image](https://user-images.githubusercontent.com/16168975/27581559-4d24d424-5b2e-11e7-97dd-3d54094acf74.png)

**Comment by dg0yt** [comment] 2017-06-27 17:33
@Zerbembasqwibo Well spotted, and easy to fix for this symbol set. However, it indicates that there are some bugs in the creation and/or transfer of certain symbols....
