### ISSUE TITLE
Import and paste data between files, coordinate issues

### ISSUE THREAD

**Issue by arenol** [OpenOrienteering/mapper#851] opened 2017-03-26 19:31 UTC
This is how I discovered the problem: I'm about to upgrade my map from ISOM2000 to the forthcomming ISOM2017.  At a point I discovered that the "Allways oriented to north (not rotatable)" check box was checked for my boulder field symbol.  As a consequence, all my boulder field triangle instances was oriented to north.  Unfortunately unchecking the option did not help.  The rotation was lost.

The solution, I thought, was to copy and paste the symbols back from an older map with the rotation attribute intact.  However, it turned out that both when I pasted the symbols into my map, and when I try to import them from a file, they ended up (literally) hundred of miles a way from where grey should be.  It took my an hour to move them in place, one screen at a time, screen by screen at the smallest zoom level.

### Steps to reproduce
1. Dublicate an .omap file
2. Open both in OOM.
3. Select and copy all objects of one feature in file 1.
4. Paste them into file 2.

Alternatively.
3. Delete all objects but one feature from file 1 and save it.
4. Import file1 into file to using File > Import...

### Actual behaviour
The imported/pasted data, does not preserve the original coordinates, neither map coordinates nor geographic coordinates.

### Expected behaviour
In these case, the pasted/imported data should be pasted directly into the correct place,

### Configuration
Mapper Version: 0.5.7
Operating System: macOS sierra.

**Comment by dg0yt** [comment] 2017-03-27 04:05
Another duplicate of #831, which is listed as known issue for 0.6.7 and fixed in 0.6.8.

**Closed** 2017-03-27 04:05 UTC
Labels: duplicate
