### ISSUE TITLE
Hide/ Protect symbols in Android app

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#1020] opened 2017-12-05 17:14 UTC
### Expected behaviour
It would be great if handling of hiding/ protecting symbols would be possible also in Android app.

**Comment by lpechacek** [comment] 2017-12-05 17:35
Tap and hold the symbol selector button in bottom right corner, context menu will appear. The menu contains Hide, Protect and Symbol description items. I think it's documented somewhere or at least we discussed it in some of the issues here.

**Comment by dg0yt** [comment] 2017-12-05 17:53
Duplicate of #788. 

It is to be added in the app documentation before v0.8.0. (lpechacek already added it to the FAQ, http://www.openorienteering.org/mapper-manual/pages/faq.html#how-do-i-hideprotect-a-symbol-in-the-mobile-ui)

**Closed by dg0yt** 2017-12-05 17:53 UTC

**Comment by ollesmaps** [comment] 2017-12-05 19:33
That is terriffic. Sorry for the duplicate. I will go again through all the manual and FAQ.

**Comment by ollesmaps** [comment] 2018-01-23 10:38
Could a checkbox for **Show all symbols** be added? When drawing I usually hide symbols one by one. That is fine, however at some point it would be faster to unhide/ unprotect all at once rather than doing it one by one.

**Comment by mlerjen** [comment] 2018-01-25 15:25
A small "bug" here. After hiding a  symbol it also gets invisible on the "actual symbol" field at the right bottom of the main view. Seems to be the case only for dashed line symbols.
![screenshots_2018-01-25-16-08-31](https://user-images.githubusercontent.com/15611653/35395943-f7459786-01eb-11e8-9c4e-e2dd868c4324.png)

**Comment by dg0yt** [comment] 2018-01-26 07:10
Thanks for tracking down the circumstances. I could reproduce the same effect  in the desktop version when changing symbol icon size. It is fixed now, and the decorators for hidden or protected state will be displayed, too.
