### ISSUE TITLE
Nothing happen if try import OSM file

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1478] opened 2019-12-23 05:41 UTC
### Steps to reproduce

1. Launch *Mapper*;
2. Create new map;
3. Go to *"File > Import..."*;
4. Set filter to *"All files"*;
5. Choose `*.osm` file;
6. Click on <kbd>Open</kbd>.

### Actual behaviour

Nothing happen try import `*.osm` file via *"File > Import... > All files"* dialog.

![pic.1](https://i.imgur.com/1qSoOhj.png)

![pic.2](https://i.imgur.com/wrRIbsj.png)

If in *"File > Open"* set filters *"Importable files"* files with `*.osm` extensions not shown.

![pic.3](https://i.imgur.com/BWrCBB8.png)

### Expected behaviour

OSM files should be imported as expected.

### Configuration

- **Mapper Version:** `master 0.9.20191221` (tagged as `master v20191221.17` on GitHub)
- **Operating System:** Debian 9.x, x86_64 (OBS build)

**Comment by dg0yt** [comment] 2019-12-23 07:31
Duplicate of #1478.

**Closed by dg0yt** 2019-12-23 07:31 UTC

**Comment by pkturner** [comment] 2020-05-16 16:34
@dg0yt  I suggest re-opening this issue.  With 0.9.3 I encountered this problem again. Now I have eliminated part of the problem by reinstalling GDAL with its OSM import was enabled. However, Mapper still does _nothing_ if you try to import a file with a different unrecognized file format.
### Steps to reproduce
1. In Mapper, create a new map.
2. Using File > Import..., select a file in an unsupported format.

### Actual behaviour
The file selection dialog disappears.

### Expected behaviour
An error window should pop up and say "File format not recognized."

**Comment by dg0yt** [comment] 2020-05-16 20:09
@pkturner IIUC you only ask for an error message? The original issue was about the .osm extension being missing unexpectedly, and OSM format not being supported unexpectedly.

**Comment by pkturner** [comment] 2020-05-16 21:23
Yes. It just felt as if this issue had not been put to rest, because I experienced the same confusing behavior upon building v0.9.3 on my Gentoo Linux system.

At this point you might title the issue, "Nothing happens if try import unsupported file".
